/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ContactPaymentDto
 */
public class ContactPaymentDtoTest {
    private final ContactPaymentDto model = new ContactPaymentDto();

    /**
     * Model tests for ContactPaymentDto
     */
    @Test
    public void testContactPaymentDto() {
        // TODO: test ContactPaymentDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'fiscalName'
     */
    @Test
    public void fiscalNameTest() {
        // TODO: test fiscalName
    }

    /**
     * Test the property 'vatNumber'
     */
    @Test
    public void vatNumberTest() {
        // TODO: test vatNumber
    }

}
