/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateAccountingAccountDto
 */
public class CreateAccountingAccountDtoTest {
    private final CreateAccountingAccountDto model = new CreateAccountingAccountDto();

    /**
     * Model tests for CreateAccountingAccountDto
     */
    @Test
    public void testCreateAccountingAccountDto() {
        // TODO: test CreateAccountingAccountDto
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'alias'
     */
    @Test
    public void aliasTest() {
        // TODO: test alias
    }

    /**
     * Test the property 'IBAN'
     */
    @Test
    public void IBANTest() {
        // TODO: test IBAN
    }

    /**
     * Test the property 'swiftCode'
     */
    @Test
    public void swiftCodeTest() {
        // TODO: test swiftCode
    }

    /**
     * Test the property 'creditCardNumber'
     */
    @Test
    public void creditCardNumberTest() {
        // TODO: test creditCardNumber
    }

    /**
     * Test the property 'creditCardExpireDate'
     */
    @Test
    public void creditCardExpireDateTest() {
        // TODO: test creditCardExpireDate
    }

}
