/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.facturasbillin.sdk.model.DocumentContactDto;
import net.facturasbillin.sdk.model.ExpenseLineBaseDto;
import net.facturasbillin.sdk.model.ExpenseTaxLineBaseDto;
import net.facturasbillin.sdk.model.ExpenseTotalDto;
import net.facturasbillin.sdk.model.VisualLineDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ExpenseCreateDto
 */
public class ExpenseCreateDtoTest {
    private final ExpenseCreateDto model = new ExpenseCreateDto();

    /**
     * Model tests for ExpenseCreateDto
     */
    @Test
    public void testExpenseCreateDto() {
        // TODO: test ExpenseCreateDto
    }

    /**
     * Test the property 'visualLines'
     */
    @Test
    public void visualLinesTest() {
        // TODO: test visualLines
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'isPaid'
     */
    @Test
    public void isPaidTest() {
        // TODO: test isPaid
    }

    /**
     * Test the property 'retentionAmount'
     */
    @Test
    public void retentionAmountTest() {
        // TODO: test retentionAmount
    }

    /**
     * Test the property 'retentionPercentage'
     */
    @Test
    public void retentionPercentageTest() {
        // TODO: test retentionPercentage
    }

    /**
     * Test the property 'identifier'
     */
    @Test
    public void identifierTest() {
        // TODO: test identifier
    }

    /**
     * Test the property 'issuedDate'
     */
    @Test
    public void issuedDateTest() {
        // TODO: test issuedDate
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    public void dueDateTest() {
        // TODO: test dueDate
    }

    /**
     * Test the property 'lines'
     */
    @Test
    public void linesTest() {
        // TODO: test lines
    }

    /**
     * Test the property 'taxLines'
     */
    @Test
    public void taxLinesTest() {
        // TODO: test taxLines
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'contact'
     */
    @Test
    public void contactTest() {
        // TODO: test contact
    }

}
