/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import net.facturasbillin.sdk.model.GetAddressAnswerDto;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.facturasbillin.sdk.JSON;

/**
 * BusinessBaseAnswerDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class BusinessBaseAnswerDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_FISCAL_NAME = "fiscalName";
  @SerializedName(SERIALIZED_NAME_FISCAL_NAME)
  private String fiscalName;

  public static final String SERIALIZED_NAME_VAT_NUMBER = "vatNumber";
  @SerializedName(SERIALIZED_NAME_VAT_NUMBER)
  private String vatNumber;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private GetAddressAnswerDto address;

  public BusinessBaseAnswerDto() {
  }

  public BusinessBaseAnswerDto fiscalName(String fiscalName) {
    this.fiscalName = fiscalName;
    return this;
  }

   /**
   * The name of the business
   * @return fiscalName
  **/
  @javax.annotation.Nonnull
  @NotNull

  public String getFiscalName() {
    return fiscalName;
  }

  public void setFiscalName(String fiscalName) {
    this.fiscalName = fiscalName;
  }


  public BusinessBaseAnswerDto vatNumber(String vatNumber) {
    this.vatNumber = vatNumber;
    return this;
  }

   /**
   * The VAT Identification number of the business
   * @return vatNumber
  **/
  @javax.annotation.Nonnull
  @NotNull

  public String getVatNumber() {
    return vatNumber;
  }

  public void setVatNumber(String vatNumber) {
    this.vatNumber = vatNumber;
  }


  public BusinessBaseAnswerDto address(GetAddressAnswerDto address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  public GetAddressAnswerDto getAddress() {
    return address;
  }

  public void setAddress(GetAddressAnswerDto address) {
    this.address = address;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessBaseAnswerDto businessBaseAnswerDto = (BusinessBaseAnswerDto) o;
    return Objects.equals(this.fiscalName, businessBaseAnswerDto.fiscalName) &&
        Objects.equals(this.vatNumber, businessBaseAnswerDto.vatNumber) &&
        Objects.equals(this.address, businessBaseAnswerDto.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fiscalName, vatNumber, address);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessBaseAnswerDto {\n");
    sb.append("    fiscalName: ").append(toIndentedString(fiscalName)).append("\n");
    sb.append("    vatNumber: ").append(toIndentedString(vatNumber)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("fiscalName");
    openapiFields.add("vatNumber");
    openapiFields.add("address");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("fiscalName");
    openapiRequiredFields.add("vatNumber");
    openapiRequiredFields.add("address");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BusinessBaseAnswerDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BusinessBaseAnswerDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BusinessBaseAnswerDto is not found in the empty JSON string", BusinessBaseAnswerDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BusinessBaseAnswerDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BusinessBaseAnswerDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BusinessBaseAnswerDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("fiscalName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fiscalName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fiscalName").toString()));
      }
      if (!jsonObj.get("vatNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vatNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vatNumber").toString()));
      }
      // validate the required field `address`
      GetAddressAnswerDto.validateJsonElement(jsonObj.get("address"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BusinessBaseAnswerDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BusinessBaseAnswerDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BusinessBaseAnswerDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BusinessBaseAnswerDto.class));

       return (TypeAdapter<T>) new TypeAdapter<BusinessBaseAnswerDto>() {
           @Override
           public void write(JsonWriter out, BusinessBaseAnswerDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BusinessBaseAnswerDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BusinessBaseAnswerDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BusinessBaseAnswerDto
  * @throws IOException if the JSON string is invalid with respect to BusinessBaseAnswerDto
  */
  public static BusinessBaseAnswerDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BusinessBaseAnswerDto.class);
  }

 /**
  * Convert an instance of BusinessBaseAnswerDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

