/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.facturasbillin.sdk.model.BusinessBaseAnswerDto;
import net.facturasbillin.sdk.model.DocumentContactAnswerDto;
import net.facturasbillin.sdk.model.DocumentLineAnswerDto;
import net.facturasbillin.sdk.model.DocumentTaxLineAnswerDto;
import net.facturasbillin.sdk.model.DocumentTotalAnswerDto;
import net.facturasbillin.sdk.model.GetPaymentMethodDto;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.facturasbillin.sdk.JSON;

/**
 * ExpenseDocumentAnswerDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ExpenseDocumentAnswerDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_ISSUED_DATE_TIME = "issuedDateTime";
  @SerializedName(SERIALIZED_NAME_ISSUED_DATE_TIME)
  private OffsetDateTime issuedDateTime;

  public static final String SERIALIZED_NAME_ISSUED_DATE = "issuedDate";
  @SerializedName(SERIALIZED_NAME_ISSUED_DATE)
  private String issuedDate;

  public static final String SERIALIZED_NAME_OWNER_INFO = "ownerInfo";
  @SerializedName(SERIALIZED_NAME_OWNER_INFO)
  private BusinessBaseAnswerDto ownerInfo;

  /**
   * Currency used on the document
   */
  @JsonAdapter(CurrencyEnum.Adapter.class)
  public enum CurrencyEnum {
    ALL("ALL"),
    
    AFN("AFN"),
    
    ARS("ARS"),
    
    AWG("AWG"),
    
    AUD("AUD"),
    
    AZN("AZN"),
    
    BBD("BBD"),
    
    BDT("BDT"),
    
    BGN("BGN"),
    
    BMD("BMD"),
    
    BND("BND"),
    
    BOB("BOB"),
    
    BAM("BAM"),
    
    BWP("BWP"),
    
    BRL("BRL"),
    
    BZD("BZD"),
    
    CAD("CAD"),
    
    KYD("KYD"),
    
    CLP("CLP"),
    
    CNY("CNY"),
    
    COP("COP"),
    
    CRC("CRC"),
    
    HRK("HRK"),
    
    CUP("CUP"),
    
    CZK("CZK"),
    
    DKK("DKK"),
    
    DOP("DOP"),
    
    XCD("XCD"),
    
    EGP("EGP"),
    
    SVC("SVC"),
    
    EUR("EUR"),
    
    FKP("FKP"),
    
    FJD("FJD"),
    
    GHS("GHS"),
    
    GIP("GIP"),
    
    GTQ("GTQ"),
    
    GGP("GGP"),
    
    GYD("GYD"),
    
    HNL("HNL"),
    
    HKD("HKD"),
    
    HUF("HUF"),
    
    ISK("ISK"),
    
    INR("INR"),
    
    IDR("IDR"),
    
    IRR("IRR"),
    
    IMP("IMP"),
    
    ILS("ILS"),
    
    JMD("JMD"),
    
    JPY("JPY"),
    
    JEP("JEP"),
    
    KZT("KZT"),
    
    KPW("KPW"),
    
    KGS("KGS"),
    
    LAK("LAK"),
    
    LBP("LBP"),
    
    LRD("LRD"),
    
    MKD("MKD"),
    
    MYR("MYR"),
    
    MUR("MUR"),
    
    MXN("MXN"),
    
    MNT("MNT"),
    
    MZN("MZN"),
    
    NAD("NAD"),
    
    NPR("NPR"),
    
    ANG("ANG"),
    
    NZD("NZD"),
    
    NIO("NIO"),
    
    NGN("NGN"),
    
    NOK("NOK"),
    
    OMR("OMR"),
    
    PKR("PKR"),
    
    PAB("PAB"),
    
    PYG("PYG"),
    
    PEN("PEN"),
    
    PHP("PHP"),
    
    PLN("PLN"),
    
    QAR("QAR"),
    
    RON("RON"),
    
    RUB("RUB"),
    
    SHP("SHP"),
    
    SAR("SAR"),
    
    RSD("RSD"),
    
    SCR("SCR"),
    
    SGD("SGD"),
    
    SBD("SBD"),
    
    SOS("SOS"),
    
    KRW("KRW"),
    
    ZAR("ZAR"),
    
    LKR("LKR"),
    
    SEK("SEK"),
    
    CHF("CHF"),
    
    SRD("SRD"),
    
    SYP("SYP"),
    
    TWD("TWD"),
    
    THB("THB"),
    
    TTD("TTD"),
    
    TRY("TRY"),
    
    TVD("TVD"),
    
    UAH("UAH"),
    
    AED("AED"),
    
    GBP("GBP"),
    
    USD("USD"),
    
    UYU("UYU"),
    
    UZS("UZS"),
    
    VEF("VEF"),
    
    VND("VND"),
    
    YER("YER"),
    
    XOF("XOF"),
    
    ZWD("ZWD");

    private String value;

    CurrencyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CurrencyEnum fromValue(String value) {
      for (CurrencyEnum b : CurrencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CurrencyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CurrencyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CurrencyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CurrencyEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CurrencyEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private CurrencyEnum currency;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  private String comments;

  public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER)
  private String identifier;

  public static final String SERIALIZED_NAME_CONTACT = "contact";
  @SerializedName(SERIALIZED_NAME_CONTACT)
  private DocumentContactAnswerDto contact;

  public static final String SERIALIZED_NAME_LINES = "lines";
  @SerializedName(SERIALIZED_NAME_LINES)
  private List<DocumentLineAnswerDto> lines;

  public static final String SERIALIZED_NAME_TAX_LINES = "taxLines";
  @SerializedName(SERIALIZED_NAME_TAX_LINES)
  private List<DocumentTaxLineAnswerDto> taxLines;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private DocumentTotalAnswerDto total;

  public static final String SERIALIZED_NAME_RETENTION_PERCENTAGE = "retentionPercentage";
  @SerializedName(SERIALIZED_NAME_RETENTION_PERCENTAGE)
  private BigDecimal retentionPercentage;

  public static final String SERIALIZED_NAME_RETENTION_AMOUNT = "retentionAmount";
  @SerializedName(SERIALIZED_NAME_RETENTION_AMOUNT)
  private BigDecimal retentionAmount;

  public static final String SERIALIZED_NAME_PAID_AMOUNT = "paidAmount";
  @SerializedName(SERIALIZED_NAME_PAID_AMOUNT)
  private BigDecimal paidAmount;

  public static final String SERIALIZED_NAME_IS_PAID = "isPaid";
  @SerializedName(SERIALIZED_NAME_IS_PAID)
  private Boolean isPaid;

  public static final String SERIALIZED_NAME_DUE_DATE = "dueDate";
  @SerializedName(SERIALIZED_NAME_DUE_DATE)
  private String dueDate;

  public static final String SERIALIZED_NAME_PAYMENT_METHODS = "paymentMethods";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHODS)
  private GetPaymentMethodDto paymentMethods;

  /**
   * Type of the document
   */
  @JsonAdapter(CategoryEnum.Adapter.class)
  public enum CategoryEnum {
    _206_SOFTWARE_APPLICATIONS("206_SOFTWARE_APPLICATIONS"),
    
    _210_LAND_AND_NATURAL_RESOURCES("210_LAND_AND_NATURAL_RESOURCES"),
    
    _211_BUILDINGS("211_BUILDINGS"),
    
    _212_TECHNICAL_INSTALLATIONS("212_TECHNICAL_INSTALLATIONS"),
    
    _213_MACHINERY("213_MACHINERY"),
    
    _214_TOOLS("214_TOOLS"),
    
    _215_OTHER_INSTALLATIONS("215_OTHER_INSTALLATIONS"),
    
    _216_FURNITURE("216_FURNITURE"),
    
    _217_INFORMATION_PROCESSING_EQUIPMENT("217_INFORMATION_PROCESSING_EQUIPMENT"),
    
    _218_TRANSPORT_ELEMENTS("218_TRANSPORT_ELEMENTS"),
    
    _219_OTHER_TANGIBLE_ASSETS("219_OTHER_TANGIBLE_ASSETS"),
    
    _600_WARE("600_WARE"),
    
    _601_RAW_MATERIALS("601_RAW_MATERIALS"),
    
    _602_SUPPLIES("602_SUPPLIES"),
    
    _607_OTHER_COMPANIES("607_OTHER_COMPANIES"),
    
    _608_RETURNS("608_RETURNS"),
    
    _610_VARIATIONS_MERCHADISE("610_VARIATIONS_MERCHADISE"),
    
    _611_VARIATIONS_RAW_MATERIALS("611_VARIATIONS_RAW_MATERIALS"),
    
    _612_VARIATIONS_OTHER_SUPPLIES("612_VARIATIONS_OTHER_SUPPLIES"),
    
    _620_VARIATIONS_OTHER_SUPPLIES("620_VARIATIONS_OTHER_SUPPLIES"),
    
    _621_RENTING("621_RENTING"),
    
    _622_REPAIRS_AND_MAINTENANCE("622_REPAIRS_AND_MAINTENANCE"),
    
    _623_RETENTION_SERVICES("623_RETENTION_SERVICES"),
    
    _624_LOGISTICS("624_LOGISTICS"),
    
    _625_INSURANCE("625_INSURANCE"),
    
    _626_BANKING_EXPENSES("626_BANKING_EXPENSES"),
    
    _627_ADVERTISING("627_ADVERTISING"),
    
    _628_GENERAL_SUPPLIES("628_GENERAL_SUPPLIES"),
    
    _629_OTHER_SERVICES("629_OTHER_SERVICES"),
    
    _630_CURRENT_TAX("630_CURRENT_TAX"),
    
    _6301_DEFERRED_TAX("6301_DEFERRED_TAX"),
    
    _631_OTHER_TAXES("631_OTHER_TAXES"),
    
    _640_SALARY("640_SALARY"),
    
    _641_INDEMNIFICATIONS("641_INDEMNIFICATIONS"),
    
    _642_SOCIAL_SECURITY_TAXES("642_SOCIAL_SECURITY_TAXES"),
    
    _649_SOCIAL_EXPENSES("649_SOCIAL_EXPENSES"),
    
    _6623_BANK_DEBT_INTEREST("6623_BANK_DEBT_INTEREST"),
    
    _6624_INTEREST_DEBTS_OTHER_COMPANIES("6624_INTEREST_DEBTS_OTHER_COMPANIES"),
    
    _668_TANGIBLE_FIXED_EQUIPMENT("668_TANGIBLE_FIXED_EQUIPMENT"),
    
    _669_OTHER_FINANCIAL_EXPENSES("669_OTHER_FINANCIAL_EXPENSES"),
    
    _678_EXCEPTIONAL_EXPENSES("678_EXCEPTIONAL_EXPENSES"),
    
    _680_AMORTIZATION_INTANGIBLE_FIXED_ASSETS("680_AMORTIZATION_INTANGIBLE_FIXED_ASSETS"),
    
    _681_AMORTIZATION_PROPERTY_AND_EQUIPMENT("681_AMORTIZATION_PROPERTY_AND_EQUIPMENT"),
    
    _682_AMORTIZATION_INVESTMENT_PROPERTY("682_AMORTIZATION_INVESTMENT_PROPERTY"),
    
    UNCATEGORIZED("UNCATEGORIZED"),
    
    OTHER("OTHER"),
    
    OWED("OWED");

    private String value;

    CategoryEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CategoryEnum fromValue(String value) {
      for (CategoryEnum b : CategoryEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CategoryEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CategoryEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CategoryEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CategoryEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CategoryEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private CategoryEnum category;

  public static final String SERIALIZED_NAME_IS_EXPENSE = "isExpense";
  @SerializedName(SERIALIZED_NAME_IS_EXPENSE)
  private Object isExpense;

  public ExpenseDocumentAnswerDto() {
  }

  public ExpenseDocumentAnswerDto id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The id of the document
   * @return id
  **/
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public ExpenseDocumentAnswerDto createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The date when the document was created
   * @return createdAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ExpenseDocumentAnswerDto updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The date when the document was last updated
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ExpenseDocumentAnswerDto issuedDateTime(OffsetDateTime issuedDateTime) {
    this.issuedDateTime = issuedDateTime;
    return this;
  }

   /**
   * The datetime when the document was issued
   * @return issuedDateTime
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getIssuedDateTime() {
    return issuedDateTime;
  }

  public void setIssuedDateTime(OffsetDateTime issuedDateTime) {
    this.issuedDateTime = issuedDateTime;
  }


  public ExpenseDocumentAnswerDto issuedDate(String issuedDate) {
    this.issuedDate = issuedDate;
    return this;
  }

   /**
   * The date when the document was issued
   * @return issuedDate
  **/
  @javax.annotation.Nullable
  public String getIssuedDate() {
    return issuedDate;
  }

  public void setIssuedDate(String issuedDate) {
    this.issuedDate = issuedDate;
  }


  public ExpenseDocumentAnswerDto ownerInfo(BusinessBaseAnswerDto ownerInfo) {
    this.ownerInfo = ownerInfo;
    return this;
  }

   /**
   * Get ownerInfo
   * @return ownerInfo
  **/
  @javax.annotation.Nullable
  public BusinessBaseAnswerDto getOwnerInfo() {
    return ownerInfo;
  }

  public void setOwnerInfo(BusinessBaseAnswerDto ownerInfo) {
    this.ownerInfo = ownerInfo;
  }


  public ExpenseDocumentAnswerDto currency(CurrencyEnum currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency used on the document
   * @return currency
  **/
  @javax.annotation.Nullable
  public CurrencyEnum getCurrency() {
    return currency;
  }

  public void setCurrency(CurrencyEnum currency) {
    this.currency = currency;
  }


  public ExpenseDocumentAnswerDto comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Comments of the document
   * @return comments
  **/
  @javax.annotation.Nullable
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }


  public ExpenseDocumentAnswerDto identifier(String identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * The identifier of the document
   * @return identifier
  **/
  @javax.annotation.Nullable
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }


  public ExpenseDocumentAnswerDto contact(DocumentContactAnswerDto contact) {
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  @javax.annotation.Nullable
  public DocumentContactAnswerDto getContact() {
    return contact;
  }

  public void setContact(DocumentContactAnswerDto contact) {
    this.contact = contact;
  }


  public ExpenseDocumentAnswerDto lines(List<DocumentLineAnswerDto> lines) {
    this.lines = lines;
    return this;
  }

  public ExpenseDocumentAnswerDto addLinesItem(DocumentLineAnswerDto linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<>();
    }
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Lines of the document
   * @return lines
  **/
  @javax.annotation.Nullable
  public List<DocumentLineAnswerDto> getLines() {
    return lines;
  }

  public void setLines(List<DocumentLineAnswerDto> lines) {
    this.lines = lines;
  }


  public ExpenseDocumentAnswerDto taxLines(List<DocumentTaxLineAnswerDto> taxLines) {
    this.taxLines = taxLines;
    return this;
  }

  public ExpenseDocumentAnswerDto addTaxLinesItem(DocumentTaxLineAnswerDto taxLinesItem) {
    if (this.taxLines == null) {
      this.taxLines = new ArrayList<>();
    }
    this.taxLines.add(taxLinesItem);
    return this;
  }

   /**
   * Tax lines of the expense document
   * @return taxLines
  **/
  @javax.annotation.Nullable
  public List<DocumentTaxLineAnswerDto> getTaxLines() {
    return taxLines;
  }

  public void setTaxLines(List<DocumentTaxLineAnswerDto> taxLines) {
    this.taxLines = taxLines;
  }


  public ExpenseDocumentAnswerDto total(DocumentTotalAnswerDto total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @javax.annotation.Nullable
  public DocumentTotalAnswerDto getTotal() {
    return total;
  }

  public void setTotal(DocumentTotalAnswerDto total) {
    this.total = total;
  }


  public ExpenseDocumentAnswerDto retentionPercentage(BigDecimal retentionPercentage) {
    this.retentionPercentage = retentionPercentage;
    return this;
  }

   /**
   * Percentage of retention
   * @return retentionPercentage
  **/
  @javax.annotation.Nullable
  public BigDecimal getRetentionPercentage() {
    return retentionPercentage;
  }

  public void setRetentionPercentage(BigDecimal retentionPercentage) {
    this.retentionPercentage = retentionPercentage;
  }


  public ExpenseDocumentAnswerDto retentionAmount(BigDecimal retentionAmount) {
    this.retentionAmount = retentionAmount;
    return this;
  }

   /**
   * Retention amount
   * @return retentionAmount
  **/
  @javax.annotation.Nullable
  public BigDecimal getRetentionAmount() {
    return retentionAmount;
  }

  public void setRetentionAmount(BigDecimal retentionAmount) {
    this.retentionAmount = retentionAmount;
  }


  public ExpenseDocumentAnswerDto paidAmount(BigDecimal paidAmount) {
    this.paidAmount = paidAmount;
    return this;
  }

   /**
   * Paid amount
   * @return paidAmount
  **/
  @javax.annotation.Nullable
  public BigDecimal getPaidAmount() {
    return paidAmount;
  }

  public void setPaidAmount(BigDecimal paidAmount) {
    this.paidAmount = paidAmount;
  }


  public ExpenseDocumentAnswerDto isPaid(Boolean isPaid) {
    this.isPaid = isPaid;
    return this;
  }

   /**
   * True if the document is paid
   * @return isPaid
  **/
  @javax.annotation.Nullable
  public Boolean getIsPaid() {
    return isPaid;
  }

  public void setIsPaid(Boolean isPaid) {
    this.isPaid = isPaid;
  }


  public ExpenseDocumentAnswerDto dueDate(String dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * The due date of the document
   * @return dueDate
  **/
  @javax.annotation.Nullable
  public String getDueDate() {
    return dueDate;
  }

  public void setDueDate(String dueDate) {
    this.dueDate = dueDate;
  }


  public ExpenseDocumentAnswerDto paymentMethods(GetPaymentMethodDto paymentMethods) {
    this.paymentMethods = paymentMethods;
    return this;
  }

   /**
   * Get paymentMethods
   * @return paymentMethods
  **/
  @javax.annotation.Nullable
  public GetPaymentMethodDto getPaymentMethods() {
    return paymentMethods;
  }

  public void setPaymentMethods(GetPaymentMethodDto paymentMethods) {
    this.paymentMethods = paymentMethods;
  }


  public ExpenseDocumentAnswerDto category(CategoryEnum category) {
    this.category = category;
    return this;
  }

   /**
   * Type of the document
   * @return category
  **/
  @javax.annotation.Nullable
  public CategoryEnum getCategory() {
    return category;
  }

  public void setCategory(CategoryEnum category) {
    this.category = category;
  }


  public ExpenseDocumentAnswerDto isExpense(Object isExpense) {
    this.isExpense = isExpense;
    return this;
  }

   /**
   * Boolean indicating if the document is an expense
   * @return isExpense
  **/
  @javax.annotation.Nullable
  public Object getIsExpense() {
    return isExpense;
  }

  public void setIsExpense(Object isExpense) {
    this.isExpense = isExpense;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ExpenseDocumentAnswerDto instance itself
   */
  public ExpenseDocumentAnswerDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpenseDocumentAnswerDto expenseDocumentAnswerDto = (ExpenseDocumentAnswerDto) o;
    return Objects.equals(this.id, expenseDocumentAnswerDto.id) &&
        Objects.equals(this.createdAt, expenseDocumentAnswerDto.createdAt) &&
        Objects.equals(this.updatedAt, expenseDocumentAnswerDto.updatedAt) &&
        Objects.equals(this.issuedDateTime, expenseDocumentAnswerDto.issuedDateTime) &&
        Objects.equals(this.issuedDate, expenseDocumentAnswerDto.issuedDate) &&
        Objects.equals(this.ownerInfo, expenseDocumentAnswerDto.ownerInfo) &&
        Objects.equals(this.currency, expenseDocumentAnswerDto.currency) &&
        Objects.equals(this.comments, expenseDocumentAnswerDto.comments) &&
        Objects.equals(this.identifier, expenseDocumentAnswerDto.identifier) &&
        Objects.equals(this.contact, expenseDocumentAnswerDto.contact) &&
        Objects.equals(this.lines, expenseDocumentAnswerDto.lines) &&
        Objects.equals(this.taxLines, expenseDocumentAnswerDto.taxLines) &&
        Objects.equals(this.total, expenseDocumentAnswerDto.total) &&
        Objects.equals(this.retentionPercentage, expenseDocumentAnswerDto.retentionPercentage) &&
        Objects.equals(this.retentionAmount, expenseDocumentAnswerDto.retentionAmount) &&
        Objects.equals(this.paidAmount, expenseDocumentAnswerDto.paidAmount) &&
        Objects.equals(this.isPaid, expenseDocumentAnswerDto.isPaid) &&
        Objects.equals(this.dueDate, expenseDocumentAnswerDto.dueDate) &&
        Objects.equals(this.paymentMethods, expenseDocumentAnswerDto.paymentMethods) &&
        Objects.equals(this.category, expenseDocumentAnswerDto.category) &&
        Objects.equals(this.isExpense, expenseDocumentAnswerDto.isExpense)&&
        Objects.equals(this.additionalProperties, expenseDocumentAnswerDto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, updatedAt, issuedDateTime, issuedDate, ownerInfo, currency, comments, identifier, contact, lines, taxLines, total, retentionPercentage, retentionAmount, paidAmount, isPaid, dueDate, paymentMethods, category, isExpense, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpenseDocumentAnswerDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    issuedDateTime: ").append(toIndentedString(issuedDateTime)).append("\n");
    sb.append("    issuedDate: ").append(toIndentedString(issuedDate)).append("\n");
    sb.append("    ownerInfo: ").append(toIndentedString(ownerInfo)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    taxLines: ").append(toIndentedString(taxLines)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    retentionPercentage: ").append(toIndentedString(retentionPercentage)).append("\n");
    sb.append("    retentionAmount: ").append(toIndentedString(retentionAmount)).append("\n");
    sb.append("    paidAmount: ").append(toIndentedString(paidAmount)).append("\n");
    sb.append("    isPaid: ").append(toIndentedString(isPaid)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    paymentMethods: ").append(toIndentedString(paymentMethods)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    isExpense: ").append(toIndentedString(isExpense)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("issuedDateTime");
    openapiFields.add("issuedDate");
    openapiFields.add("ownerInfo");
    openapiFields.add("currency");
    openapiFields.add("comments");
    openapiFields.add("identifier");
    openapiFields.add("contact");
    openapiFields.add("lines");
    openapiFields.add("taxLines");
    openapiFields.add("total");
    openapiFields.add("retentionPercentage");
    openapiFields.add("retentionAmount");
    openapiFields.add("paidAmount");
    openapiFields.add("isPaid");
    openapiFields.add("dueDate");
    openapiFields.add("paymentMethods");
    openapiFields.add("category");
    openapiFields.add("isExpense");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element. Made tolerant via the SDK template override:
  * any non-object payload (e.g. the API returning {@code []} where the spec
  * says object) is silently ignored, and field-level type mismatches are
  * swallowed, so a malformed field never crashes the whole DTO.
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ExpenseDocumentAnswerDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null || jsonElement.isJsonNull()) {
        if (!ExpenseDocumentAnswerDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExpenseDocumentAnswerDto is not found in the empty JSON string", ExpenseDocumentAnswerDto.openapiRequiredFields.toString()));
        }
        return;
      }
      // SDK tolerance: when the API returns a shape other than a JSON object
      // (e.g. an empty array []), do not crash deserialization. The reflective
      // adapter will leave the field null and the caller can handle absence.
      if (!jsonElement.isJsonObject()) {
        return;
      }
      try {
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `currency`
      if (jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull() && jsonObj.get("currency").isJsonPrimitive()) {
        CurrencyEnum.validateJsonElement(jsonObj.get("currency"));
      }
      // SDK tolerance: optional array fields tolerate non-array shapes silently
      // SDK tolerance: optional array fields tolerate non-array shapes silently
      // validate the optional field `category`
      if (jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull() && jsonObj.get("category").isJsonPrimitive()) {
        CategoryEnum.validateJsonElement(jsonObj.get("category"));
      }
      } catch (RuntimeException ignored) {
        // SDK tolerance: per-field validation failures (unknown keys, wrong
        // primitive types, etc.) must not crash the whole response. The
        // reflective Gson adapter that runs next will leave problematic
        // fields null when conversion is impossible.
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExpenseDocumentAnswerDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExpenseDocumentAnswerDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExpenseDocumentAnswerDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExpenseDocumentAnswerDto.class));

       return (TypeAdapter<T>) new TypeAdapter<ExpenseDocumentAnswerDto>() {
           @Override
           public void write(JsonWriter out, ExpenseDocumentAnswerDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else if (entry.getValue() == null)
                   obj.add(entry.getKey(), null);
                 else {
                   JsonElement tree = gson.toJsonTree(entry.getValue());
                   if (tree.isJsonObject()) {
                     obj.add(entry.getKey(), tree.getAsJsonObject());
                   } else {
                     obj.add(entry.getKey(), tree);
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ExpenseDocumentAnswerDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             // SDK tolerance: API may return a non-object shape (commonly `[]`)
             // where the spec declares this type. Don't crash — return null.
             if (jsonElement == null || jsonElement.isJsonNull() || !jsonElement.isJsonObject()) {
               return null;
             }
             try {
               validateJsonElement(jsonElement);
             } catch (RuntimeException ignored) {
               // SDK tolerance: validation already swallows internally, but
               // belt-and-braces in case a future change throws unexpectedly.
             }
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ExpenseDocumentAnswerDto instance;
             try {
               instance = thisAdapter.fromJsonTree(jsonObj);
             } catch (RuntimeException ignored) {
               // SDK tolerance: a single field with a wildly wrong shape can
               // make the reflective adapter throw. Better to lose the DTO
               // than to crash the entire API call.
               return null;
             }
             if (instance == null) {
               return null;
             }
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 try {
                   JsonElement value = entry.getValue();
                   if (value == null || value.isJsonNull()) {
                     instance.putAdditionalProperty(entry.getKey(), null);
                   } else if (value.isJsonPrimitive()) { // primitive type
                     if (value.getAsJsonPrimitive().isString())
                       instance.putAdditionalProperty(entry.getKey(), value.getAsString());
                     else if (value.getAsJsonPrimitive().isNumber())
                       instance.putAdditionalProperty(entry.getKey(), value.getAsNumber());
                     else if (value.getAsJsonPrimitive().isBoolean())
                       instance.putAdditionalProperty(entry.getKey(), value.getAsBoolean());
                     else
                       instance.putAdditionalProperty(entry.getKey(), value.toString());
                   } else if (value.isJsonArray()) {
                       instance.putAdditionalProperty(entry.getKey(), gson.fromJson(value, List.class));
                   } else { // JSON object
                       instance.putAdditionalProperty(entry.getKey(), gson.fromJson(value, HashMap.class));
                   }
                 } catch (RuntimeException ignored) {
                   // SDK tolerance: skip additional properties that can't be deserialized.
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExpenseDocumentAnswerDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExpenseDocumentAnswerDto
  * @throws IOException if the JSON string is invalid with respect to ExpenseDocumentAnswerDto
  */
  public static ExpenseDocumentAnswerDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExpenseDocumentAnswerDto.class);
  }

 /**
  * Convert an instance of ExpenseDocumentAnswerDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

