/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.facturasbillin.sdk.JSON;

/**
 * ExpenseTaxLineBaseDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ExpenseTaxLineBaseDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_TAX_KEY = "taxKey";
  @SerializedName(SERIALIZED_NAME_TAX_KEY)
  private String taxKey;

  public static final String SERIALIZED_NAME_TAX_BASE = "taxBase";
  @SerializedName(SERIALIZED_NAME_TAX_BASE)
  private BigDecimal taxBase;

  public static final String SERIALIZED_NAME_TAX_PERCENTAGE = "taxPercentage";
  @SerializedName(SERIALIZED_NAME_TAX_PERCENTAGE)
  private BigDecimal taxPercentage;

  public static final String SERIALIZED_NAME_TAX_AMOUNT = "taxAmount";
  @SerializedName(SERIALIZED_NAME_TAX_AMOUNT)
  private BigDecimal taxAmount;

  public ExpenseTaxLineBaseDto() {
  }

  public ExpenseTaxLineBaseDto taxKey(String taxKey) {
    this.taxKey = taxKey;
    return this;
  }

   /**
   * It must have the format TAXTYPE_INT, TAXTYPE_INT_INT or TAXTYPE_NONTAXABLETAXTYPE_INT.  The TAXTYPE can be IVA, IPSI or IGIC. INT is the tax rate and the second INT is for the decimal part of the tax rate. The NONTAXABLETAXTYPE can be Exempt, NotSubject or ReverseCharge. For the NONTAXABLETAXTYPE the INT must be 0. Some examples are: IVA_Exempt_0, IVA_21, IPSI_3, IGIC_7_5
   * @return taxKey
  **/
  @javax.annotation.Nonnull
  @NotNull

  public String getTaxKey() {
    return taxKey;
  }

  public void setTaxKey(String taxKey) {
    this.taxKey = taxKey;
  }


  public ExpenseTaxLineBaseDto taxBase(BigDecimal taxBase) {
    this.taxBase = taxBase;
    return this;
  }

   /**
   * Price without taxes
   * @return taxBase
  **/
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  public BigDecimal getTaxBase() {
    return taxBase;
  }

  public void setTaxBase(BigDecimal taxBase) {
    this.taxBase = taxBase;
  }


  public ExpenseTaxLineBaseDto taxPercentage(BigDecimal taxPercentage) {
    this.taxPercentage = taxPercentage;
    return this;
  }

   /**
   * Tax percentage
   * @return taxPercentage
  **/
  @javax.annotation.Nullable
  @Valid

  public BigDecimal getTaxPercentage() {
    return taxPercentage;
  }

  public void setTaxPercentage(BigDecimal taxPercentage) {
    this.taxPercentage = taxPercentage;
  }


  public ExpenseTaxLineBaseDto taxAmount(BigDecimal taxAmount) {
    this.taxAmount = taxAmount;
    return this;
  }

   /**
   * Amount tax to be deducted from the price
   * @return taxAmount
  **/
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  public BigDecimal getTaxAmount() {
    return taxAmount;
  }

  public void setTaxAmount(BigDecimal taxAmount) {
    this.taxAmount = taxAmount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpenseTaxLineBaseDto expenseTaxLineBaseDto = (ExpenseTaxLineBaseDto) o;
    return Objects.equals(this.taxKey, expenseTaxLineBaseDto.taxKey) &&
        Objects.equals(this.taxBase, expenseTaxLineBaseDto.taxBase) &&
        Objects.equals(this.taxPercentage, expenseTaxLineBaseDto.taxPercentage) &&
        Objects.equals(this.taxAmount, expenseTaxLineBaseDto.taxAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(taxKey, taxBase, taxPercentage, taxAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpenseTaxLineBaseDto {\n");
    sb.append("    taxKey: ").append(toIndentedString(taxKey)).append("\n");
    sb.append("    taxBase: ").append(toIndentedString(taxBase)).append("\n");
    sb.append("    taxPercentage: ").append(toIndentedString(taxPercentage)).append("\n");
    sb.append("    taxAmount: ").append(toIndentedString(taxAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("taxKey");
    openapiFields.add("taxBase");
    openapiFields.add("taxPercentage");
    openapiFields.add("taxAmount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("taxKey");
    openapiRequiredFields.add("taxBase");
    openapiRequiredFields.add("taxAmount");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ExpenseTaxLineBaseDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ExpenseTaxLineBaseDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExpenseTaxLineBaseDto is not found in the empty JSON string", ExpenseTaxLineBaseDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ExpenseTaxLineBaseDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ExpenseTaxLineBaseDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ExpenseTaxLineBaseDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("taxKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `taxKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("taxKey").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExpenseTaxLineBaseDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExpenseTaxLineBaseDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExpenseTaxLineBaseDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExpenseTaxLineBaseDto.class));

       return (TypeAdapter<T>) new TypeAdapter<ExpenseTaxLineBaseDto>() {
           @Override
           public void write(JsonWriter out, ExpenseTaxLineBaseDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExpenseTaxLineBaseDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ExpenseTaxLineBaseDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ExpenseTaxLineBaseDto
  * @throws IOException if the JSON string is invalid with respect to ExpenseTaxLineBaseDto
  */
  public static ExpenseTaxLineBaseDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExpenseTaxLineBaseDto.class);
  }

 /**
  * Convert an instance of ExpenseTaxLineBaseDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

