/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.facturasbillin.sdk.model.QueryDto;
import net.facturasbillin.sdk.model.SortDto;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.facturasbillin.sdk.JSON;

/**
 * GetPaymentListQueryDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetPaymentListQueryDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_OFFSET = "offset";
  @SerializedName(SERIALIZED_NAME_OFFSET)
  private BigDecimal offset = new BigDecimal("0");

  public static final String SERIALIZED_NAME_LIMIT = "limit";
  @SerializedName(SERIALIZED_NAME_LIMIT)
  private BigDecimal limit = new BigDecimal("10");

  public static final String SERIALIZED_NAME_SORT = "sort";
  @SerializedName(SERIALIZED_NAME_SORT)
  private SortDto sort;

  public static final String SERIALIZED_NAME_QUERY = "query";
  @SerializedName(SERIALIZED_NAME_QUERY)
  private QueryDto query;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private List<String> fields = new ArrayList<>();

  public static final String SERIALIZED_NAME_CUSTOM_SEARCH_FIELDS = "customSearchFields";
  @SerializedName(SERIALIZED_NAME_CUSTOM_SEARCH_FIELDS)
  private List<String> customSearchFields = new ArrayList<>();

  public GetPaymentListQueryDto() {
  }

  public GetPaymentListQueryDto offset(BigDecimal offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Get offset
   * minimum: 0
   * @return offset
  **/
  @javax.annotation.Nullable
  public BigDecimal getOffset() {
    return offset;
  }

  public void setOffset(BigDecimal offset) {
    this.offset = offset;
  }


  public GetPaymentListQueryDto limit(BigDecimal limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * minimum: 0
   * maximum: 100
   * @return limit
  **/
  @javax.annotation.Nullable
  public BigDecimal getLimit() {
    return limit;
  }

  public void setLimit(BigDecimal limit) {
    this.limit = limit;
  }


  public GetPaymentListQueryDto sort(SortDto sort) {
    this.sort = sort;
    return this;
  }

   /**
   * Get sort
   * @return sort
  **/
  @javax.annotation.Nullable
  public SortDto getSort() {
    return sort;
  }

  public void setSort(SortDto sort) {
    this.sort = sort;
  }


  public GetPaymentListQueryDto query(QueryDto query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @javax.annotation.Nullable
  public QueryDto getQuery() {
    return query;
  }

  public void setQuery(QueryDto query) {
    this.query = query;
  }


  public GetPaymentListQueryDto fields(List<String> fields) {
    this.fields = fields;
    return this;
  }

  public GetPaymentListQueryDto addFieldsItem(String fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @javax.annotation.Nullable
  public List<String> getFields() {
    return fields;
  }

  public void setFields(List<String> fields) {
    this.fields = fields;
  }


  public GetPaymentListQueryDto customSearchFields(List<String> customSearchFields) {
    this.customSearchFields = customSearchFields;
    return this;
  }

  public GetPaymentListQueryDto addCustomSearchFieldsItem(String customSearchFieldsItem) {
    if (this.customSearchFields == null) {
      this.customSearchFields = new ArrayList<>();
    }
    this.customSearchFields.add(customSearchFieldsItem);
    return this;
  }

   /**
   * Get customSearchFields
   * @return customSearchFields
  **/
  @javax.annotation.Nullable
  public List<String> getCustomSearchFields() {
    return customSearchFields;
  }

  public void setCustomSearchFields(List<String> customSearchFields) {
    this.customSearchFields = customSearchFields;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GetPaymentListQueryDto instance itself
   */
  public GetPaymentListQueryDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPaymentListQueryDto getPaymentListQueryDto = (GetPaymentListQueryDto) o;
    return Objects.equals(this.offset, getPaymentListQueryDto.offset) &&
        Objects.equals(this.limit, getPaymentListQueryDto.limit) &&
        Objects.equals(this.sort, getPaymentListQueryDto.sort) &&
        Objects.equals(this.query, getPaymentListQueryDto.query) &&
        Objects.equals(this.fields, getPaymentListQueryDto.fields) &&
        Objects.equals(this.customSearchFields, getPaymentListQueryDto.customSearchFields)&&
        Objects.equals(this.additionalProperties, getPaymentListQueryDto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offset, limit, sort, query, fields, customSearchFields, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPaymentListQueryDto {\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    customSearchFields: ").append(toIndentedString(customSearchFields)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("offset");
    openapiFields.add("limit");
    openapiFields.add("sort");
    openapiFields.add("query");
    openapiFields.add("fields");
    openapiFields.add("customSearchFields");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element. Made tolerant via the SDK template override:
  * any non-object payload (e.g. the API returning {@code []} where the spec
  * says object) is silently ignored, and field-level type mismatches are
  * swallowed, so a malformed field never crashes the whole DTO.
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to GetPaymentListQueryDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null || jsonElement.isJsonNull()) {
        if (!GetPaymentListQueryDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetPaymentListQueryDto is not found in the empty JSON string", GetPaymentListQueryDto.openapiRequiredFields.toString()));
        }
        return;
      }
      // SDK tolerance: when the API returns a shape other than a JSON object
      // (e.g. an empty array []), do not crash deserialization. The reflective
      // adapter will leave the field null and the caller can handle absence.
      if (!jsonElement.isJsonObject()) {
        return;
      }
      try {
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // SDK tolerance: optional array fields tolerate non-array shapes silently
      // SDK tolerance: optional array fields tolerate non-array shapes silently
      } catch (RuntimeException ignored) {
        // SDK tolerance: per-field validation failures (unknown keys, wrong
        // primitive types, etc.) must not crash the whole response. The
        // reflective Gson adapter that runs next will leave problematic
        // fields null when conversion is impossible.
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetPaymentListQueryDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetPaymentListQueryDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetPaymentListQueryDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetPaymentListQueryDto.class));

       return (TypeAdapter<T>) new TypeAdapter<GetPaymentListQueryDto>() {
           @Override
           public void write(JsonWriter out, GetPaymentListQueryDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else if (entry.getValue() == null)
                   obj.add(entry.getKey(), null);
                 else {
                   JsonElement tree = gson.toJsonTree(entry.getValue());
                   if (tree.isJsonObject()) {
                     obj.add(entry.getKey(), tree.getAsJsonObject());
                   } else {
                     obj.add(entry.getKey(), tree);
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GetPaymentListQueryDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             // SDK tolerance: API may return a non-object shape (commonly `[]`)
             // where the spec declares this type. Don't crash — return null.
             if (jsonElement == null || jsonElement.isJsonNull() || !jsonElement.isJsonObject()) {
               return null;
             }
             try {
               validateJsonElement(jsonElement);
             } catch (RuntimeException ignored) {
               // SDK tolerance: validation already swallows internally, but
               // belt-and-braces in case a future change throws unexpectedly.
             }
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             GetPaymentListQueryDto instance;
             try {
               instance = thisAdapter.fromJsonTree(jsonObj);
             } catch (RuntimeException ignored) {
               // SDK tolerance: a single field with a wildly wrong shape can
               // make the reflective adapter throw. Better to lose the DTO
               // than to crash the entire API call.
               return null;
             }
             if (instance == null) {
               return null;
             }
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 try {
                   JsonElement value = entry.getValue();
                   if (value == null || value.isJsonNull()) {
                     instance.putAdditionalProperty(entry.getKey(), null);
                   } else if (value.isJsonPrimitive()) { // primitive type
                     if (value.getAsJsonPrimitive().isString())
                       instance.putAdditionalProperty(entry.getKey(), value.getAsString());
                     else if (value.getAsJsonPrimitive().isNumber())
                       instance.putAdditionalProperty(entry.getKey(), value.getAsNumber());
                     else if (value.getAsJsonPrimitive().isBoolean())
                       instance.putAdditionalProperty(entry.getKey(), value.getAsBoolean());
                     else
                       instance.putAdditionalProperty(entry.getKey(), value.toString());
                   } else if (value.isJsonArray()) {
                       instance.putAdditionalProperty(entry.getKey(), gson.fromJson(value, List.class));
                   } else { // JSON object
                       instance.putAdditionalProperty(entry.getKey(), gson.fromJson(value, HashMap.class));
                   }
                 } catch (RuntimeException ignored) {
                   // SDK tolerance: skip additional properties that can't be deserialized.
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetPaymentListQueryDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetPaymentListQueryDto
  * @throws IOException if the JSON string is invalid with respect to GetPaymentListQueryDto
  */
  public static GetPaymentListQueryDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetPaymentListQueryDto.class);
  }

 /**
  * Convert an instance of GetPaymentListQueryDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

