/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.facturasbillin.sdk.JSON;

/**
 * ProductAnswerDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ProductAnswerDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_REFERENCE = "reference";
  @SerializedName(SERIALIZED_NAME_REFERENCE)
  private String reference;

  public static final String SERIALIZED_NAME_TAX_KEY = "taxKey";
  @SerializedName(SERIALIZED_NAME_TAX_KEY)
  private String taxKey;

  public static final String SERIALIZED_NAME_BUYING_PRICE = "buyingPrice";
  @SerializedName(SERIALIZED_NAME_BUYING_PRICE)
  private BigDecimal buyingPrice;

  public static final String SERIALIZED_NAME_SELLING_PRICE = "sellingPrice";
  @SerializedName(SERIALIZED_NAME_SELLING_PRICE)
  private BigDecimal sellingPrice;

  public static final String SERIALIZED_NAME_RETAIL_PRICE = "retailPrice";
  @SerializedName(SERIALIZED_NAME_RETAIL_PRICE)
  private BigDecimal retailPrice;

  public static final String SERIALIZED_NAME_DISCOUNT_PERCENTAGE = "discountPercentage";
  @SerializedName(SERIALIZED_NAME_DISCOUNT_PERCENTAGE)
  private BigDecimal discountPercentage;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_MARGIN_PERCENTAGE = "marginPercentage";
  @SerializedName(SERIALIZED_NAME_MARGIN_PERCENTAGE)
  private BigDecimal marginPercentage;

  public ProductAnswerDto() {
  }

  public ProductAnswerDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the product
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public ProductAnswerDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the product
   * @return description
  **/
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  public ProductAnswerDto reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Reference of the product
   * @return reference
  **/
  @javax.annotation.Nullable
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }


  public ProductAnswerDto taxKey(String taxKey) {
    this.taxKey = taxKey;
    return this;
  }

   /**
   * It must have the format TAXTYPE_INT, TAXTYPE_INT_INT or TAXTYPE_NONTAXABLETAXTYPE_INT.  The TAXTYPE can be IVA, IPSI or IGIC. INT is the tax rate and the second INT is for the decimal part of the tax rate. The NONTAXABLETAXTYPE can be Exempt, NotSubject or ReverseCharge. For the NONTAXABLETAXTYPE the INT must be 0. Only spanish or european tax keys are allowed. Some examples are: IVA_Exempt_0, IVA_21, IPSI_3, IGIC_7_5
   * @return taxKey
  **/
  @javax.annotation.Nullable
  public String getTaxKey() {
    return taxKey;
  }

  public void setTaxKey(String taxKey) {
    this.taxKey = taxKey;
  }


  public ProductAnswerDto buyingPrice(BigDecimal buyingPrice) {
    this.buyingPrice = buyingPrice;
    return this;
  }

   /**
   * Buying price of the product
   * minimum: 0
   * maximum: 999999
   * @return buyingPrice
  **/
  @javax.annotation.Nullable
  public BigDecimal getBuyingPrice() {
    return buyingPrice;
  }

  public void setBuyingPrice(BigDecimal buyingPrice) {
    this.buyingPrice = buyingPrice;
  }


  public ProductAnswerDto sellingPrice(BigDecimal sellingPrice) {
    this.sellingPrice = sellingPrice;
    return this;
  }

   /**
   * Selling price of the product without VAT. If not provided, it will be calculated automatically.
   * minimum: 0
   * maximum: 999999
   * @return sellingPrice
  **/
  @javax.annotation.Nullable
  public BigDecimal getSellingPrice() {
    return sellingPrice;
  }

  public void setSellingPrice(BigDecimal sellingPrice) {
    this.sellingPrice = sellingPrice;
  }


  public ProductAnswerDto retailPrice(BigDecimal retailPrice) {
    this.retailPrice = retailPrice;
    return this;
  }

   /**
   * Selling price of the product including taxes and possible discounts. If not provided, it will be calculated automatically
   * minimum: 0
   * @return retailPrice
  **/
  @javax.annotation.Nullable
  public BigDecimal getRetailPrice() {
    return retailPrice;
  }

  public void setRetailPrice(BigDecimal retailPrice) {
    this.retailPrice = retailPrice;
  }


  public ProductAnswerDto discountPercentage(BigDecimal discountPercentage) {
    this.discountPercentage = discountPercentage;
    return this;
  }

   /**
   * Discount percentage to apply to the product
   * minimum: 0
   * maximum: 100
   * @return discountPercentage
  **/
  @javax.annotation.Nullable
  public BigDecimal getDiscountPercentage() {
    return discountPercentage;
  }

  public void setDiscountPercentage(BigDecimal discountPercentage) {
    this.discountPercentage = discountPercentage;
  }


  public ProductAnswerDto id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id of the created product
   * @return id
  **/
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public ProductAnswerDto createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The date when the product was created
   * @return createdAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ProductAnswerDto updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The date when the product was last updated
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ProductAnswerDto marginPercentage(BigDecimal marginPercentage) {
    this.marginPercentage = marginPercentage;
    return this;
  }

   /**
   * Margin percentage of gross profit
   * @return marginPercentage
  **/
  @javax.annotation.Nullable
  public BigDecimal getMarginPercentage() {
    return marginPercentage;
  }

  public void setMarginPercentage(BigDecimal marginPercentage) {
    this.marginPercentage = marginPercentage;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ProductAnswerDto instance itself
   */
  public ProductAnswerDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductAnswerDto productAnswerDto = (ProductAnswerDto) o;
    return Objects.equals(this.name, productAnswerDto.name) &&
        Objects.equals(this.description, productAnswerDto.description) &&
        Objects.equals(this.reference, productAnswerDto.reference) &&
        Objects.equals(this.taxKey, productAnswerDto.taxKey) &&
        Objects.equals(this.buyingPrice, productAnswerDto.buyingPrice) &&
        Objects.equals(this.sellingPrice, productAnswerDto.sellingPrice) &&
        Objects.equals(this.retailPrice, productAnswerDto.retailPrice) &&
        Objects.equals(this.discountPercentage, productAnswerDto.discountPercentage) &&
        Objects.equals(this.id, productAnswerDto.id) &&
        Objects.equals(this.createdAt, productAnswerDto.createdAt) &&
        Objects.equals(this.updatedAt, productAnswerDto.updatedAt) &&
        Objects.equals(this.marginPercentage, productAnswerDto.marginPercentage)&&
        Objects.equals(this.additionalProperties, productAnswerDto.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, reference, taxKey, buyingPrice, sellingPrice, retailPrice, discountPercentage, id, createdAt, updatedAt, marginPercentage, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductAnswerDto {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    taxKey: ").append(toIndentedString(taxKey)).append("\n");
    sb.append("    buyingPrice: ").append(toIndentedString(buyingPrice)).append("\n");
    sb.append("    sellingPrice: ").append(toIndentedString(sellingPrice)).append("\n");
    sb.append("    retailPrice: ").append(toIndentedString(retailPrice)).append("\n");
    sb.append("    discountPercentage: ").append(toIndentedString(discountPercentage)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    marginPercentage: ").append(toIndentedString(marginPercentage)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("description");
    openapiFields.add("reference");
    openapiFields.add("taxKey");
    openapiFields.add("buyingPrice");
    openapiFields.add("sellingPrice");
    openapiFields.add("retailPrice");
    openapiFields.add("discountPercentage");
    openapiFields.add("id");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("marginPercentage");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element. Made tolerant via the SDK template override:
  * any non-object payload (e.g. the API returning {@code []} where the spec
  * says object) is silently ignored, and field-level type mismatches are
  * swallowed, so a malformed field never crashes the whole DTO.
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ProductAnswerDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null || jsonElement.isJsonNull()) {
        if (!ProductAnswerDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProductAnswerDto is not found in the empty JSON string", ProductAnswerDto.openapiRequiredFields.toString()));
        }
        return;
      }
      // SDK tolerance: when the API returns a shape other than a JSON object
      // (e.g. an empty array []), do not crash deserialization. The reflective
      // adapter will leave the field null and the caller can handle absence.
      if (!jsonElement.isJsonObject()) {
        return;
      }
      try {
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      } catch (RuntimeException ignored) {
        // SDK tolerance: per-field validation failures (unknown keys, wrong
        // primitive types, etc.) must not crash the whole response. The
        // reflective Gson adapter that runs next will leave problematic
        // fields null when conversion is impossible.
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProductAnswerDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProductAnswerDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProductAnswerDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProductAnswerDto.class));

       return (TypeAdapter<T>) new TypeAdapter<ProductAnswerDto>() {
           @Override
           public void write(JsonWriter out, ProductAnswerDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else if (entry.getValue() == null)
                   obj.add(entry.getKey(), null);
                 else {
                   JsonElement tree = gson.toJsonTree(entry.getValue());
                   if (tree.isJsonObject()) {
                     obj.add(entry.getKey(), tree.getAsJsonObject());
                   } else {
                     obj.add(entry.getKey(), tree);
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ProductAnswerDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             // SDK tolerance: API may return a non-object shape (commonly `[]`)
             // where the spec declares this type. Don't crash — return null.
             if (jsonElement == null || jsonElement.isJsonNull() || !jsonElement.isJsonObject()) {
               return null;
             }
             try {
               validateJsonElement(jsonElement);
             } catch (RuntimeException ignored) {
               // SDK tolerance: validation already swallows internally, but
               // belt-and-braces in case a future change throws unexpectedly.
             }
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ProductAnswerDto instance;
             try {
               instance = thisAdapter.fromJsonTree(jsonObj);
             } catch (RuntimeException ignored) {
               // SDK tolerance: a single field with a wildly wrong shape can
               // make the reflective adapter throw. Better to lose the DTO
               // than to crash the entire API call.
               return null;
             }
             if (instance == null) {
               return null;
             }
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 try {
                   JsonElement value = entry.getValue();
                   if (value == null || value.isJsonNull()) {
                     instance.putAdditionalProperty(entry.getKey(), null);
                   } else if (value.isJsonPrimitive()) { // primitive type
                     if (value.getAsJsonPrimitive().isString())
                       instance.putAdditionalProperty(entry.getKey(), value.getAsString());
                     else if (value.getAsJsonPrimitive().isNumber())
                       instance.putAdditionalProperty(entry.getKey(), value.getAsNumber());
                     else if (value.getAsJsonPrimitive().isBoolean())
                       instance.putAdditionalProperty(entry.getKey(), value.getAsBoolean());
                     else
                       instance.putAdditionalProperty(entry.getKey(), value.toString());
                   } else if (value.isJsonArray()) {
                       instance.putAdditionalProperty(entry.getKey(), gson.fromJson(value, List.class));
                   } else { // JSON object
                       instance.putAdditionalProperty(entry.getKey(), gson.fromJson(value, HashMap.class));
                   }
                 } catch (RuntimeException ignored) {
                   // SDK tolerance: skip additional properties that can't be deserialized.
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProductAnswerDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProductAnswerDto
  * @throws IOException if the JSON string is invalid with respect to ProductAnswerDto
  */
  public static ProductAnswerDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProductAnswerDto.class);
  }

 /**
  * Convert an instance of ProductAnswerDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

