/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.facturasbillin.sdk.model.AdditionalExpenseDto;
import net.facturasbillin.sdk.model.DocumentContactDto;
import net.facturasbillin.sdk.model.DocumentLineDto;
import net.facturasbillin.sdk.model.DocumentTaxLineBaseDto;
import net.facturasbillin.sdk.model.DocumentTotalDto;
import net.facturasbillin.sdk.model.VisualLineDto;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.facturasbillin.sdk.JSON;

/**
 * QuoteCreateDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class QuoteCreateDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_SERIE_ID = "serieId";
  @SerializedName(SERIALIZED_NAME_SERIE_ID)
  private String serieId;

  public static final String SERIALIZED_NAME_SERIAL_CODE = "serialCode";
  @SerializedName(SERIALIZED_NAME_SERIAL_CODE)
  private String serialCode;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private BigDecimal code;

  public static final String SERIALIZED_NAME_MASK = "mask";
  @SerializedName(SERIALIZED_NAME_MASK)
  private BigDecimal mask;

  public static final String SERIALIZED_NAME_ISSUED_DATE = "issuedDate";
  @SerializedName(SERIALIZED_NAME_ISSUED_DATE)
  private String issuedDate;

  public static final String SERIALIZED_NAME_REFERENCE = "reference";
  @SerializedName(SERIALIZED_NAME_REFERENCE)
  private String reference;

  public static final String SERIALIZED_NAME_VISUAL_LINES = "visualLines";
  @SerializedName(SERIALIZED_NAME_VISUAL_LINES)
  private List<@Valid VisualLineDto> visualLines;

  public static final String SERIALIZED_NAME_TAX_LINES = "taxLines";
  @SerializedName(SERIALIZED_NAME_TAX_LINES)
  private List<@Valid DocumentTaxLineBaseDto> taxLines;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  private String comments;

  /**
   * Currency used on the document
   */
  @JsonAdapter(CurrencyEnum.Adapter.class)
  public enum CurrencyEnum {
    ALL("ALL"),
    
    AFN("AFN"),
    
    ARS("ARS"),
    
    AWG("AWG"),
    
    AUD("AUD"),
    
    AZN("AZN"),
    
    BBD("BBD"),
    
    BDT("BDT"),
    
    BGN("BGN"),
    
    BMD("BMD"),
    
    BND("BND"),
    
    BOB("BOB"),
    
    BAM("BAM"),
    
    BWP("BWP"),
    
    BRL("BRL"),
    
    BZD("BZD"),
    
    CAD("CAD"),
    
    KYD("KYD"),
    
    CLP("CLP"),
    
    CNY("CNY"),
    
    COP("COP"),
    
    CRC("CRC"),
    
    HRK("HRK"),
    
    CUP("CUP"),
    
    CZK("CZK"),
    
    DKK("DKK"),
    
    DOP("DOP"),
    
    XCD("XCD"),
    
    EGP("EGP"),
    
    SVC("SVC"),
    
    EUR("EUR"),
    
    FKP("FKP"),
    
    FJD("FJD"),
    
    GHS("GHS"),
    
    GIP("GIP"),
    
    GTQ("GTQ"),
    
    GGP("GGP"),
    
    GYD("GYD"),
    
    HNL("HNL"),
    
    HKD("HKD"),
    
    HUF("HUF"),
    
    ISK("ISK"),
    
    INR("INR"),
    
    IDR("IDR"),
    
    IRR("IRR"),
    
    IMP("IMP"),
    
    ILS("ILS"),
    
    JMD("JMD"),
    
    JPY("JPY"),
    
    JEP("JEP"),
    
    KZT("KZT"),
    
    KPW("KPW"),
    
    KGS("KGS"),
    
    LAK("LAK"),
    
    LBP("LBP"),
    
    LRD("LRD"),
    
    MKD("MKD"),
    
    MYR("MYR"),
    
    MUR("MUR"),
    
    MXN("MXN"),
    
    MNT("MNT"),
    
    MZN("MZN"),
    
    NAD("NAD"),
    
    NPR("NPR"),
    
    ANG("ANG"),
    
    NZD("NZD"),
    
    NIO("NIO"),
    
    NGN("NGN"),
    
    NOK("NOK"),
    
    OMR("OMR"),
    
    PKR("PKR"),
    
    PAB("PAB"),
    
    PYG("PYG"),
    
    PEN("PEN"),
    
    PHP("PHP"),
    
    PLN("PLN"),
    
    QAR("QAR"),
    
    RON("RON"),
    
    RUB("RUB"),
    
    SHP("SHP"),
    
    SAR("SAR"),
    
    RSD("RSD"),
    
    SCR("SCR"),
    
    SGD("SGD"),
    
    SBD("SBD"),
    
    SOS("SOS"),
    
    KRW("KRW"),
    
    ZAR("ZAR"),
    
    LKR("LKR"),
    
    SEK("SEK"),
    
    CHF("CHF"),
    
    SRD("SRD"),
    
    SYP("SYP"),
    
    TWD("TWD"),
    
    THB("THB"),
    
    TTD("TTD"),
    
    TRY("TRY"),
    
    TVD("TVD"),
    
    UAH("UAH"),
    
    AED("AED"),
    
    GBP("GBP"),
    
    USD("USD"),
    
    UYU("UYU"),
    
    UZS("UZS"),
    
    VEF("VEF"),
    
    VND("VND"),
    
    YER("YER"),
    
    XOF("XOF"),
    
    ZWD("ZWD");

    private String value;

    CurrencyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CurrencyEnum fromValue(String value) {
      for (CurrencyEnum b : CurrencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CurrencyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CurrencyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CurrencyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CurrencyEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CurrencyEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private CurrencyEnum currency;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private DocumentTotalDto total;

  public static final String SERIALIZED_NAME_PAID_AMOUNT = "paidAmount";
  @SerializedName(SERIALIZED_NAME_PAID_AMOUNT)
  private BigDecimal paidAmount;

  public static final String SERIALIZED_NAME_RETENTION_AMOUNT = "retentionAmount";
  @SerializedName(SERIALIZED_NAME_RETENTION_AMOUNT)
  private BigDecimal retentionAmount;

  public static final String SERIALIZED_NAME_RETENTION_PERCENTAGE = "retentionPercentage";
  @SerializedName(SERIALIZED_NAME_RETENTION_PERCENTAGE)
  private BigDecimal retentionPercentage;

  public static final String SERIALIZED_NAME_SHOW_PRODUCT_REFERENCE = "showProductReference";
  @SerializedName(SERIALIZED_NAME_SHOW_PRODUCT_REFERENCE)
  private Boolean showProductReference = false;

  public static final String SERIALIZED_NAME_LINES = "lines";
  @SerializedName(SERIALIZED_NAME_LINES)
  private List<@Valid DocumentLineDto> lines = new ArrayList<>();

  public static final String SERIALIZED_NAME_DUE_DATE = "dueDate";
  @SerializedName(SERIALIZED_NAME_DUE_DATE)
  private String dueDate;

  public static final String SERIALIZED_NAME_ADDITIONAL_EXPENSES = "additionalExpenses";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_EXPENSES)
  private List<@Valid AdditionalExpenseDto> additionalExpenses = new ArrayList<>();

  public static final String SERIALIZED_NAME_TEMPLATE_ID = "templateId";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_ID)
  private String templateId;

  public static final String SERIALIZED_NAME_CONTACT = "contact";
  @SerializedName(SERIALIZED_NAME_CONTACT)
  private DocumentContactDto contact;

  public static final String SERIALIZED_NAME_SHOW_PDF_LINES_WITHOUT_TAXES = "showPdfLinesWithoutTaxes";
  @SerializedName(SERIALIZED_NAME_SHOW_PDF_LINES_WITHOUT_TAXES)
  private Boolean showPdfLinesWithoutTaxes;

  /**
   * Status of the quote
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING("PENDING"),
    
    ACCEPTED("ACCEPTED"),
    
    REJECTED("REJECTED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status = StatusEnum.PENDING;

  public QuoteCreateDto() {
  }

  public QuoteCreateDto serieId(String serieId) {
    this.serieId = serieId;
    return this;
  }

   /**
   * The id of the serie. If provided together with serialCode, the serieId will be used
   * @return serieId
  **/
  @javax.annotation.Nullable

  public String getSerieId() {
    return serieId;
  }

  public void setSerieId(String serieId) {
    this.serieId = serieId;
  }


  public QuoteCreateDto serialCode(String serialCode) {
    this.serialCode = serialCode;
    return this;
  }

   /**
   * Serial Code of the document. If provided together with serieId, the serieId will be used
   * @return serialCode
  **/
  @javax.annotation.Nullable

  public String getSerialCode() {
    return serialCode;
  }

  public void setSerialCode(String serialCode) {
    this.serialCode = serialCode;
  }


  public QuoteCreateDto code(BigDecimal code) {
    this.code = code;
    return this;
  }

   /**
   * Code/Number of the document
   * minimum: 0
   * maximum: 1000000000
   * @return code
  **/
  @javax.annotation.Nullable
  @Valid
 @DecimalMin("0") @DecimalMax("1000000000")
  public BigDecimal getCode() {
    return code;
  }

  public void setCode(BigDecimal code) {
    this.code = code;
  }


  public QuoteCreateDto mask(BigDecimal mask) {
    this.mask = mask;
    return this;
  }

   /**
   * Mask used on the code of the document. The complete invoice identifier number is built from the serial code and the code. For example, for a serial code \&quot;F2023\&quot; and a code \&quot;1\&quot; the full identifier number that will appear in the PDF will be \&quot;F20231\&quot;. The mask allows for leading zeros to be included when constructing the complete ID number in the PDF. If we put a mask of 3, the full ID number will be \&quot;F2023001\&quot;
   * minimum: 0
   * maximum: 1000000000
   * @return mask
  **/
  @javax.annotation.Nullable
  @Valid
 @DecimalMin("0") @DecimalMax("1000000000")
  public BigDecimal getMask() {
    return mask;
  }

  public void setMask(BigDecimal mask) {
    this.mask = mask;
  }


  public QuoteCreateDto issuedDate(String issuedDate) {
    this.issuedDate = issuedDate;
    return this;
  }

   /**
   * The date when the documen was issued
   * @return issuedDate
  **/
  @javax.annotation.Nullable

  public String getIssuedDate() {
    return issuedDate;
  }

  public void setIssuedDate(String issuedDate) {
    this.issuedDate = issuedDate;
  }


  public QuoteCreateDto reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * The reference of the document
   * @return reference
  **/
  @javax.annotation.Nullable

  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }


  public QuoteCreateDto visualLines(List<@Valid VisualLineDto> visualLines) {
    this.visualLines = visualLines;
    return this;
  }

  public QuoteCreateDto addVisualLinesItem(VisualLineDto visualLinesItem) {
    if (this.visualLines == null) {
      this.visualLines = new ArrayList<>();
    }
    this.visualLines.add(visualLinesItem);
    return this;
  }

   /**
   * Visual Lines of the document
   * @return visualLines
  **/
  @javax.annotation.Nullable
  @Valid

  public List<@Valid VisualLineDto> getVisualLines() {
    return visualLines;
  }

  public void setVisualLines(List<@Valid VisualLineDto> visualLines) {
    this.visualLines = visualLines;
  }


  public QuoteCreateDto taxLines(List<@Valid DocumentTaxLineBaseDto> taxLines) {
    this.taxLines = taxLines;
    return this;
  }

  public QuoteCreateDto addTaxLinesItem(DocumentTaxLineBaseDto taxLinesItem) {
    if (this.taxLines == null) {
      this.taxLines = new ArrayList<>();
    }
    this.taxLines.add(taxLinesItem);
    return this;
  }

   /**
   * Tax lines of the document. If not provided, they will be calculated from the lines
   * @return taxLines
  **/
  @javax.annotation.Nullable
  @Valid

  public List<@Valid DocumentTaxLineBaseDto> getTaxLines() {
    return taxLines;
  }

  public void setTaxLines(List<@Valid DocumentTaxLineBaseDto> taxLines) {
    this.taxLines = taxLines;
  }


  public QuoteCreateDto comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Comments of the document
   * @return comments
  **/
  @javax.annotation.Nullable

  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }


  public QuoteCreateDto currency(CurrencyEnum currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency used on the document
   * @return currency
  **/
  @javax.annotation.Nonnull
  @NotNull

  public CurrencyEnum getCurrency() {
    return currency;
  }

  public void setCurrency(CurrencyEnum currency) {
    this.currency = currency;
  }


  public QuoteCreateDto total(DocumentTotalDto total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @javax.annotation.Nullable
  @Valid

  public DocumentTotalDto getTotal() {
    return total;
  }

  public void setTotal(DocumentTotalDto total) {
    this.total = total;
  }


  public QuoteCreateDto paidAmount(BigDecimal paidAmount) {
    this.paidAmount = paidAmount;
    return this;
  }

   /**
   * Paid amount
   * @return paidAmount
  **/
  @javax.annotation.Nullable
  @Valid

  public BigDecimal getPaidAmount() {
    return paidAmount;
  }

  public void setPaidAmount(BigDecimal paidAmount) {
    this.paidAmount = paidAmount;
  }


  public QuoteCreateDto retentionAmount(BigDecimal retentionAmount) {
    this.retentionAmount = retentionAmount;
    return this;
  }

   /**
   * Amount of retention. If this property is set it will override retentionPercentage if it is also set
   * @return retentionAmount
  **/
  @javax.annotation.Nullable
  @Valid

  public BigDecimal getRetentionAmount() {
    return retentionAmount;
  }

  public void setRetentionAmount(BigDecimal retentionAmount) {
    this.retentionAmount = retentionAmount;
  }


  public QuoteCreateDto retentionPercentage(BigDecimal retentionPercentage) {
    this.retentionPercentage = retentionPercentage;
    return this;
  }

   /**
   * Percentage of retention
   * @return retentionPercentage
  **/
  @javax.annotation.Nullable
  @Valid

  public BigDecimal getRetentionPercentage() {
    return retentionPercentage;
  }

  public void setRetentionPercentage(BigDecimal retentionPercentage) {
    this.retentionPercentage = retentionPercentage;
  }


  public QuoteCreateDto showProductReference(Boolean showProductReference) {
    this.showProductReference = showProductReference;
    return this;
  }

   /**
   * True if product reference should be shown in Pdf
   * @return showProductReference
  **/
  @javax.annotation.Nullable

  public Boolean getShowProductReference() {
    return showProductReference;
  }

  public void setShowProductReference(Boolean showProductReference) {
    this.showProductReference = showProductReference;
  }


  public QuoteCreateDto lines(List<@Valid DocumentLineDto> lines) {
    this.lines = lines;
    return this;
  }

  public QuoteCreateDto addLinesItem(DocumentLineDto linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<>();
    }
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Lines of the document
   * @return lines
  **/
  @javax.annotation.Nonnull
  @NotNull
  @Valid
 @Size(min=1)
  public List<@Valid DocumentLineDto> getLines() {
    return lines;
  }

  public void setLines(List<@Valid DocumentLineDto> lines) {
    this.lines = lines;
  }


  public QuoteCreateDto dueDate(String dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Due date of the quote
   * @return dueDate
  **/
  @javax.annotation.Nullable

  public String getDueDate() {
    return dueDate;
  }

  public void setDueDate(String dueDate) {
    this.dueDate = dueDate;
  }


  public QuoteCreateDto additionalExpenses(List<@Valid AdditionalExpenseDto> additionalExpenses) {
    this.additionalExpenses = additionalExpenses;
    return this;
  }

  public QuoteCreateDto addAdditionalExpensesItem(AdditionalExpenseDto additionalExpensesItem) {
    if (this.additionalExpenses == null) {
      this.additionalExpenses = new ArrayList<>();
    }
    this.additionalExpenses.add(additionalExpensesItem);
    return this;
  }

   /**
   * Additional expenses of the quote
   * @return additionalExpenses
  **/
  @javax.annotation.Nullable
  @Valid

  public List<@Valid AdditionalExpenseDto> getAdditionalExpenses() {
    return additionalExpenses;
  }

  public void setAdditionalExpenses(List<@Valid AdditionalExpenseDto> additionalExpenses) {
    this.additionalExpenses = additionalExpenses;
  }


  public QuoteCreateDto templateId(String templateId) {
    this.templateId = templateId;
    return this;
  }

   /**
   * The id of the template to use for the quote
   * @return templateId
  **/
  @javax.annotation.Nullable

  public String getTemplateId() {
    return templateId;
  }

  public void setTemplateId(String templateId) {
    this.templateId = templateId;
  }


  public QuoteCreateDto contact(DocumentContactDto contact) {
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  public DocumentContactDto getContact() {
    return contact;
  }

  public void setContact(DocumentContactDto contact) {
    this.contact = contact;
  }


  public QuoteCreateDto showPdfLinesWithoutTaxes(Boolean showPdfLinesWithoutTaxes) {
    this.showPdfLinesWithoutTaxes = showPdfLinesWithoutTaxes;
    return this;
  }

   /**
   * Check this if you want to show the lines without taxes in the PDF visualization in Billin&#39;s web app
   * @return showPdfLinesWithoutTaxes
  **/
  @javax.annotation.Nullable

  public Boolean getShowPdfLinesWithoutTaxes() {
    return showPdfLinesWithoutTaxes;
  }

  public void setShowPdfLinesWithoutTaxes(Boolean showPdfLinesWithoutTaxes) {
    this.showPdfLinesWithoutTaxes = showPdfLinesWithoutTaxes;
  }


  public QuoteCreateDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the quote
   * @return status
  **/
  @javax.annotation.Nullable

  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuoteCreateDto quoteCreateDto = (QuoteCreateDto) o;
    return Objects.equals(this.serieId, quoteCreateDto.serieId) &&
        Objects.equals(this.serialCode, quoteCreateDto.serialCode) &&
        Objects.equals(this.code, quoteCreateDto.code) &&
        Objects.equals(this.mask, quoteCreateDto.mask) &&
        Objects.equals(this.issuedDate, quoteCreateDto.issuedDate) &&
        Objects.equals(this.reference, quoteCreateDto.reference) &&
        Objects.equals(this.visualLines, quoteCreateDto.visualLines) &&
        Objects.equals(this.taxLines, quoteCreateDto.taxLines) &&
        Objects.equals(this.comments, quoteCreateDto.comments) &&
        Objects.equals(this.currency, quoteCreateDto.currency) &&
        Objects.equals(this.total, quoteCreateDto.total) &&
        Objects.equals(this.paidAmount, quoteCreateDto.paidAmount) &&
        Objects.equals(this.retentionAmount, quoteCreateDto.retentionAmount) &&
        Objects.equals(this.retentionPercentage, quoteCreateDto.retentionPercentage) &&
        Objects.equals(this.showProductReference, quoteCreateDto.showProductReference) &&
        Objects.equals(this.lines, quoteCreateDto.lines) &&
        Objects.equals(this.dueDate, quoteCreateDto.dueDate) &&
        Objects.equals(this.additionalExpenses, quoteCreateDto.additionalExpenses) &&
        Objects.equals(this.templateId, quoteCreateDto.templateId) &&
        Objects.equals(this.contact, quoteCreateDto.contact) &&
        Objects.equals(this.showPdfLinesWithoutTaxes, quoteCreateDto.showPdfLinesWithoutTaxes) &&
        Objects.equals(this.status, quoteCreateDto.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serieId, serialCode, code, mask, issuedDate, reference, visualLines, taxLines, comments, currency, total, paidAmount, retentionAmount, retentionPercentage, showProductReference, lines, dueDate, additionalExpenses, templateId, contact, showPdfLinesWithoutTaxes, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuoteCreateDto {\n");
    sb.append("    serieId: ").append(toIndentedString(serieId)).append("\n");
    sb.append("    serialCode: ").append(toIndentedString(serialCode)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    mask: ").append(toIndentedString(mask)).append("\n");
    sb.append("    issuedDate: ").append(toIndentedString(issuedDate)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    visualLines: ").append(toIndentedString(visualLines)).append("\n");
    sb.append("    taxLines: ").append(toIndentedString(taxLines)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    paidAmount: ").append(toIndentedString(paidAmount)).append("\n");
    sb.append("    retentionAmount: ").append(toIndentedString(retentionAmount)).append("\n");
    sb.append("    retentionPercentage: ").append(toIndentedString(retentionPercentage)).append("\n");
    sb.append("    showProductReference: ").append(toIndentedString(showProductReference)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    additionalExpenses: ").append(toIndentedString(additionalExpenses)).append("\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("    showPdfLinesWithoutTaxes: ").append(toIndentedString(showPdfLinesWithoutTaxes)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("serieId");
    openapiFields.add("serialCode");
    openapiFields.add("code");
    openapiFields.add("mask");
    openapiFields.add("issuedDate");
    openapiFields.add("reference");
    openapiFields.add("visualLines");
    openapiFields.add("taxLines");
    openapiFields.add("comments");
    openapiFields.add("currency");
    openapiFields.add("total");
    openapiFields.add("paidAmount");
    openapiFields.add("retentionAmount");
    openapiFields.add("retentionPercentage");
    openapiFields.add("showProductReference");
    openapiFields.add("lines");
    openapiFields.add("dueDate");
    openapiFields.add("additionalExpenses");
    openapiFields.add("templateId");
    openapiFields.add("contact");
    openapiFields.add("showPdfLinesWithoutTaxes");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("currency");
    openapiRequiredFields.add("lines");
    openapiRequiredFields.add("contact");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to QuoteCreateDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!QuoteCreateDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in QuoteCreateDto is not found in the empty JSON string", QuoteCreateDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!QuoteCreateDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `QuoteCreateDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : QuoteCreateDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("serieId") != null && !jsonObj.get("serieId").isJsonNull()) && !jsonObj.get("serieId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serieId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serieId").toString()));
      }
      if ((jsonObj.get("serialCode") != null && !jsonObj.get("serialCode").isJsonNull()) && !jsonObj.get("serialCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serialCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serialCode").toString()));
      }
      if ((jsonObj.get("issuedDate") != null && !jsonObj.get("issuedDate").isJsonNull()) && !jsonObj.get("issuedDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `issuedDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("issuedDate").toString()));
      }
      if ((jsonObj.get("reference") != null && !jsonObj.get("reference").isJsonNull()) && !jsonObj.get("reference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reference").toString()));
      }
      if (jsonObj.get("visualLines") != null && !jsonObj.get("visualLines").isJsonNull()) {
        JsonArray jsonArrayvisualLines = jsonObj.getAsJsonArray("visualLines");
        if (jsonArrayvisualLines != null) {
          // ensure the json data is an array
          if (!jsonObj.get("visualLines").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `visualLines` to be an array in the JSON string but got `%s`", jsonObj.get("visualLines").toString()));
          }

          // validate the optional field `visualLines` (array)
          for (int i = 0; i < jsonArrayvisualLines.size(); i++) {
            VisualLineDto.validateJsonElement(jsonArrayvisualLines.get(i));
          };
        }
      }
      if (jsonObj.get("taxLines") != null && !jsonObj.get("taxLines").isJsonNull()) {
        JsonArray jsonArraytaxLines = jsonObj.getAsJsonArray("taxLines");
        if (jsonArraytaxLines != null) {
          // ensure the json data is an array
          if (!jsonObj.get("taxLines").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `taxLines` to be an array in the JSON string but got `%s`", jsonObj.get("taxLines").toString()));
          }

          // validate the optional field `taxLines` (array)
          for (int i = 0; i < jsonArraytaxLines.size(); i++) {
            DocumentTaxLineBaseDto.validateJsonElement(jsonArraytaxLines.get(i));
          };
        }
      }
      if ((jsonObj.get("comments") != null && !jsonObj.get("comments").isJsonNull()) && !jsonObj.get("comments").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comments` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comments").toString()));
      }
      if (!jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      // validate the required field `currency`
      CurrencyEnum.validateJsonElement(jsonObj.get("currency"));
      // validate the optional field `total`
      if (jsonObj.get("total") != null && !jsonObj.get("total").isJsonNull()) {
        DocumentTotalDto.validateJsonElement(jsonObj.get("total"));
      }
      // ensure the json data is an array
      if (!jsonObj.get("lines").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `lines` to be an array in the JSON string but got `%s`", jsonObj.get("lines").toString()));
      }

      JsonArray jsonArraylines = jsonObj.getAsJsonArray("lines");
      // validate the required field `lines` (array)
      for (int i = 0; i < jsonArraylines.size(); i++) {
        DocumentLineDto.validateJsonElement(jsonArraylines.get(i));
      };
      if ((jsonObj.get("dueDate") != null && !jsonObj.get("dueDate").isJsonNull()) && !jsonObj.get("dueDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dueDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dueDate").toString()));
      }
      if (jsonObj.get("additionalExpenses") != null && !jsonObj.get("additionalExpenses").isJsonNull()) {
        JsonArray jsonArrayadditionalExpenses = jsonObj.getAsJsonArray("additionalExpenses");
        if (jsonArrayadditionalExpenses != null) {
          // ensure the json data is an array
          if (!jsonObj.get("additionalExpenses").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `additionalExpenses` to be an array in the JSON string but got `%s`", jsonObj.get("additionalExpenses").toString()));
          }

          // validate the optional field `additionalExpenses` (array)
          for (int i = 0; i < jsonArrayadditionalExpenses.size(); i++) {
            AdditionalExpenseDto.validateJsonElement(jsonArrayadditionalExpenses.get(i));
          };
        }
      }
      if ((jsonObj.get("templateId") != null && !jsonObj.get("templateId").isJsonNull()) && !jsonObj.get("templateId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `templateId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("templateId").toString()));
      }
      // validate the required field `contact`
      DocumentContactDto.validateJsonElement(jsonObj.get("contact"));
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QuoteCreateDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QuoteCreateDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QuoteCreateDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QuoteCreateDto.class));

       return (TypeAdapter<T>) new TypeAdapter<QuoteCreateDto>() {
           @Override
           public void write(JsonWriter out, QuoteCreateDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public QuoteCreateDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of QuoteCreateDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of QuoteCreateDto
  * @throws IOException if the JSON string is invalid with respect to QuoteCreateDto
  */
  public static QuoteCreateDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QuoteCreateDto.class);
  }

 /**
  * Convert an instance of QuoteCreateDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

