/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import net.facturasbillin.sdk.model.AdditionalExpenseAnswerDto;
import net.facturasbillin.sdk.model.BusinessBaseAnswerDto;
import net.facturasbillin.sdk.model.DocumentContactAnswerDto;
import net.facturasbillin.sdk.model.DocumentLineAnswerDto;
import net.facturasbillin.sdk.model.DocumentTaxLineAnswerDto;
import net.facturasbillin.sdk.model.DocumentTotalAnswerDto;
import net.facturasbillin.sdk.model.GetPaymentMethodDto;
import net.facturasbillin.sdk.model.VisualLineDto;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.facturasbillin.sdk.JSON;

/**
 * QuoteDocumentAnswerDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class QuoteDocumentAnswerDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_ISSUED_DATE_TIME = "issuedDateTime";
  @SerializedName(SERIALIZED_NAME_ISSUED_DATE_TIME)
  private OffsetDateTime issuedDateTime;

  public static final String SERIALIZED_NAME_ISSUED_DATE = "issuedDate";
  @SerializedName(SERIALIZED_NAME_ISSUED_DATE)
  private String issuedDate;

  public static final String SERIALIZED_NAME_OWNER_INFO = "ownerInfo";
  @SerializedName(SERIALIZED_NAME_OWNER_INFO)
  private BusinessBaseAnswerDto ownerInfo;

  /**
   * Currency used on the document
   */
  @JsonAdapter(CurrencyEnum.Adapter.class)
  public enum CurrencyEnum {
    ALL("ALL"),
    
    AFN("AFN"),
    
    ARS("ARS"),
    
    AWG("AWG"),
    
    AUD("AUD"),
    
    AZN("AZN"),
    
    BBD("BBD"),
    
    BDT("BDT"),
    
    BGN("BGN"),
    
    BMD("BMD"),
    
    BND("BND"),
    
    BOB("BOB"),
    
    BAM("BAM"),
    
    BWP("BWP"),
    
    BRL("BRL"),
    
    BZD("BZD"),
    
    CAD("CAD"),
    
    KYD("KYD"),
    
    CLP("CLP"),
    
    CNY("CNY"),
    
    COP("COP"),
    
    CRC("CRC"),
    
    HRK("HRK"),
    
    CUP("CUP"),
    
    CZK("CZK"),
    
    DKK("DKK"),
    
    DOP("DOP"),
    
    XCD("XCD"),
    
    EGP("EGP"),
    
    SVC("SVC"),
    
    EUR("EUR"),
    
    FKP("FKP"),
    
    FJD("FJD"),
    
    GHS("GHS"),
    
    GIP("GIP"),
    
    GTQ("GTQ"),
    
    GGP("GGP"),
    
    GYD("GYD"),
    
    HNL("HNL"),
    
    HKD("HKD"),
    
    HUF("HUF"),
    
    ISK("ISK"),
    
    INR("INR"),
    
    IDR("IDR"),
    
    IRR("IRR"),
    
    IMP("IMP"),
    
    ILS("ILS"),
    
    JMD("JMD"),
    
    JPY("JPY"),
    
    JEP("JEP"),
    
    KZT("KZT"),
    
    KPW("KPW"),
    
    KGS("KGS"),
    
    LAK("LAK"),
    
    LBP("LBP"),
    
    LRD("LRD"),
    
    MKD("MKD"),
    
    MYR("MYR"),
    
    MUR("MUR"),
    
    MXN("MXN"),
    
    MNT("MNT"),
    
    MZN("MZN"),
    
    NAD("NAD"),
    
    NPR("NPR"),
    
    ANG("ANG"),
    
    NZD("NZD"),
    
    NIO("NIO"),
    
    NGN("NGN"),
    
    NOK("NOK"),
    
    OMR("OMR"),
    
    PKR("PKR"),
    
    PAB("PAB"),
    
    PYG("PYG"),
    
    PEN("PEN"),
    
    PHP("PHP"),
    
    PLN("PLN"),
    
    QAR("QAR"),
    
    RON("RON"),
    
    RUB("RUB"),
    
    SHP("SHP"),
    
    SAR("SAR"),
    
    RSD("RSD"),
    
    SCR("SCR"),
    
    SGD("SGD"),
    
    SBD("SBD"),
    
    SOS("SOS"),
    
    KRW("KRW"),
    
    ZAR("ZAR"),
    
    LKR("LKR"),
    
    SEK("SEK"),
    
    CHF("CHF"),
    
    SRD("SRD"),
    
    SYP("SYP"),
    
    TWD("TWD"),
    
    THB("THB"),
    
    TTD("TTD"),
    
    TRY("TRY"),
    
    TVD("TVD"),
    
    UAH("UAH"),
    
    AED("AED"),
    
    GBP("GBP"),
    
    USD("USD"),
    
    UYU("UYU"),
    
    UZS("UZS"),
    
    VEF("VEF"),
    
    VND("VND"),
    
    YER("YER"),
    
    XOF("XOF"),
    
    ZWD("ZWD");

    private String value;

    CurrencyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CurrencyEnum fromValue(String value) {
      for (CurrencyEnum b : CurrencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CurrencyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CurrencyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CurrencyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CurrencyEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CurrencyEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private CurrencyEnum currency;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  private String comments;

  public static final String SERIALIZED_NAME_SERIE_ID = "serieId";
  @SerializedName(SERIALIZED_NAME_SERIE_ID)
  private String serieId;

  public static final String SERIALIZED_NAME_SERIAL_CODE = "serialCode";
  @SerializedName(SERIALIZED_NAME_SERIAL_CODE)
  private String serialCode;

  public static final String SERIALIZED_NAME_MASK = "mask";
  @SerializedName(SERIALIZED_NAME_MASK)
  private BigDecimal mask;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private BigDecimal code;

  public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER)
  private String identifier;

  public static final String SERIALIZED_NAME_DUE_DATE = "dueDate";
  @SerializedName(SERIALIZED_NAME_DUE_DATE)
  private String dueDate;

  public static final String SERIALIZED_NAME_REFERENCE = "reference";
  @SerializedName(SERIALIZED_NAME_REFERENCE)
  private String reference;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private DocumentTotalAnswerDto total;

  public static final String SERIALIZED_NAME_LINES = "lines";
  @SerializedName(SERIALIZED_NAME_LINES)
  private List<DocumentLineAnswerDto> lines = new ArrayList<>();

  public static final String SERIALIZED_NAME_VISUAL_LINES = "visualLines";
  @SerializedName(SERIALIZED_NAME_VISUAL_LINES)
  private List<VisualLineDto> visualLines = new ArrayList<>();

  public static final String SERIALIZED_NAME_TAX_LINES = "taxLines";
  @SerializedName(SERIALIZED_NAME_TAX_LINES)
  private List<DocumentTaxLineAnswerDto> taxLines = new ArrayList<>();

  public static final String SERIALIZED_NAME_ADDITIONAL_EXPENSES = "additionalExpenses";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_EXPENSES)
  private List<AdditionalExpenseAnswerDto> additionalExpenses = new ArrayList<>();

  public static final String SERIALIZED_NAME_RETENTION_PERCENTAGE = "retentionPercentage";
  @SerializedName(SERIALIZED_NAME_RETENTION_PERCENTAGE)
  private BigDecimal retentionPercentage;

  public static final String SERIALIZED_NAME_RETENTION_AMOUNT = "retentionAmount";
  @SerializedName(SERIALIZED_NAME_RETENTION_AMOUNT)
  private BigDecimal retentionAmount;

  public static final String SERIALIZED_NAME_PAID_AMOUNT = "paidAmount";
  @SerializedName(SERIALIZED_NAME_PAID_AMOUNT)
  private BigDecimal paidAmount;

  /**
   * Type of the document
   */
  @JsonAdapter(DocumentTypeEnum.Adapter.class)
  public enum DocumentTypeEnum {
    INVOICE("INVOICE"),
    
    EXPENSE("EXPENSE"),
    
    QUOTE("QUOTE"),
    
    TEST_INVOICE("TEST_INVOICE"),
    
    PROFORMA_INVOICE("PROFORMA_INVOICE"),
    
    CORRECTIVE("CORRECTIVE"),
    
    DELIVERY_NOTE("DELIVERY_NOTE");

    private String value;

    DocumentTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DocumentTypeEnum fromValue(String value) {
      for (DocumentTypeEnum b : DocumentTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DocumentTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DocumentTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DocumentTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DocumentTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DocumentTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DOCUMENT_TYPE = "documentType";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_TYPE)
  private DocumentTypeEnum documentType;

  /**
   * Type of the document
   */
  @JsonAdapter(CategoryEnum.Adapter.class)
  public enum CategoryEnum {
    _600_WARE("600_WARE"),
    
    _601_RAW_MATERIALS("601_RAW_MATERIALS"),
    
    _602_SUPPLIES("602_SUPPLIES"),
    
    _607_OTHER_COMPANIES("607_OTHER_COMPANIES"),
    
    _608_RETURNS("608_RETURNS"),
    
    _610_VARIATIONS_MERCHADISE("610_VARIATIONS_MERCHADISE"),
    
    _611_VARIATIONS_RAW_MATERIALS("611_VARIATIONS_RAW_MATERIALS"),
    
    _612_VARIATIONS_OTHER_SUPPLIES("612_VARIATIONS_OTHER_SUPPLIES"),
    
    _620_VARIATIONS_OTHER_SUPPLIES("620_VARIATIONS_OTHER_SUPPLIES"),
    
    _621_RENTING("621_RENTING"),
    
    _622_REPAIRS_AND_MAINTENANCE("622_REPAIRS_AND_MAINTENANCE"),
    
    _623_RETENTION_SERVICES("623_RETENTION_SERVICES"),
    
    _624_LOGISTICS("624_LOGISTICS"),
    
    _625_INSURANCE("625_INSURANCE"),
    
    _626_BANKING_EXPENSES("626_BANKING_EXPENSES"),
    
    _627_ADVERTISING("627_ADVERTISING"),
    
    _628_GENERAL_SUPPLIES("628_GENERAL_SUPPLIES"),
    
    _629_OTHER_SERVICES("629_OTHER_SERVICES"),
    
    _630_CURRENT_TAX("630_CURRENT_TAX"),
    
    _6301_DEFERRED_TAX("6301_DEFERRED_TAX"),
    
    _631_OTHER_TAXES("631_OTHER_TAXES"),
    
    _640_SALARY("640_SALARY"),
    
    _641_INDEMNIFICATIONS("641_INDEMNIFICATIONS"),
    
    _642_SOCIAL_SECURITY_TAXES("642_SOCIAL_SECURITY_TAXES"),
    
    _649_SOCIAL_EXPENSES("649_SOCIAL_EXPENSES"),
    
    _6623_BANK_DEBT_INTEREST("6623_BANK_DEBT_INTEREST"),
    
    _6624_INTEREST_DEBTS_OTHER_COMPANIES("6624_INTEREST_DEBTS_OTHER_COMPANIES"),
    
    _668_TANGIBLE_FIXED_EQUIPMENT("668_TANGIBLE_FIXED_EQUIPMENT"),
    
    _669_OTHER_FINANCIAL_EXPENSES("669_OTHER_FINANCIAL_EXPENSES"),
    
    _678_EXCEPTIONAL_EXPENSES("678_EXCEPTIONAL_EXPENSES"),
    
    _680_AMORTIZATION_INTANGIBLE_FIXED_ASSETS("680_AMORTIZATION_INTANGIBLE_FIXED_ASSETS"),
    
    _681_AMORTIZATION_PROPERTY_AND_EQUIPMENT("681_AMORTIZATION_PROPERTY_AND_EQUIPMENT"),
    
    _682_AMORTIZATION_INVESTMENT_PROPERTY("682_AMORTIZATION_INVESTMENT_PROPERTY"),
    
    UNCATEGORIZED("UNCATEGORIZED"),
    
    OTHER("OTHER"),
    
    OWED("OWED");

    private String value;

    CategoryEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CategoryEnum fromValue(String value) {
      for (CategoryEnum b : CategoryEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CategoryEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CategoryEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CategoryEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CategoryEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CategoryEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private CategoryEnum category;

  public static final String SERIALIZED_NAME_CONTACT = "contact";
  @SerializedName(SERIALIZED_NAME_CONTACT)
  private DocumentContactAnswerDto contact;

  public static final String SERIALIZED_NAME_PAYMENT_METHODS = "paymentMethods";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHODS)
  private GetPaymentMethodDto paymentMethods;

  /**
   * Status of the quote
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING("PENDING"),
    
    ACCEPTED("ACCEPTED"),
    
    REJECTED("REJECTED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  public QuoteDocumentAnswerDto() {
  }

  public QuoteDocumentAnswerDto id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The id of the document
   * @return id
  **/
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public QuoteDocumentAnswerDto createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The date when the document was created
   * @return createdAt
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public QuoteDocumentAnswerDto updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The date when the document was last updated
   * @return updatedAt
  **/
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public QuoteDocumentAnswerDto issuedDateTime(OffsetDateTime issuedDateTime) {
    this.issuedDateTime = issuedDateTime;
    return this;
  }

   /**
   * The datetime when the document was issued
   * @return issuedDateTime
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getIssuedDateTime() {
    return issuedDateTime;
  }

  public void setIssuedDateTime(OffsetDateTime issuedDateTime) {
    this.issuedDateTime = issuedDateTime;
  }


  public QuoteDocumentAnswerDto issuedDate(String issuedDate) {
    this.issuedDate = issuedDate;
    return this;
  }

   /**
   * The date when the document was issued
   * @return issuedDate
  **/
  @javax.annotation.Nullable
  public String getIssuedDate() {
    return issuedDate;
  }

  public void setIssuedDate(String issuedDate) {
    this.issuedDate = issuedDate;
  }


  public QuoteDocumentAnswerDto ownerInfo(BusinessBaseAnswerDto ownerInfo) {
    this.ownerInfo = ownerInfo;
    return this;
  }

   /**
   * Get ownerInfo
   * @return ownerInfo
  **/
  @javax.annotation.Nonnull
  public BusinessBaseAnswerDto getOwnerInfo() {
    return ownerInfo;
  }

  public void setOwnerInfo(BusinessBaseAnswerDto ownerInfo) {
    this.ownerInfo = ownerInfo;
  }


  public QuoteDocumentAnswerDto currency(CurrencyEnum currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency used on the document
   * @return currency
  **/
  @javax.annotation.Nonnull
  public CurrencyEnum getCurrency() {
    return currency;
  }

  public void setCurrency(CurrencyEnum currency) {
    this.currency = currency;
  }


  public QuoteDocumentAnswerDto comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Comments of the document
   * @return comments
  **/
  @javax.annotation.Nullable
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }


  public QuoteDocumentAnswerDto serieId(String serieId) {
    this.serieId = serieId;
    return this;
  }

   /**
   * The id of the serie
   * @return serieId
  **/
  @javax.annotation.Nullable
  public String getSerieId() {
    return serieId;
  }

  public void setSerieId(String serieId) {
    this.serieId = serieId;
  }


  public QuoteDocumentAnswerDto serialCode(String serialCode) {
    this.serialCode = serialCode;
    return this;
  }

   /**
   * Serial Code of the document
   * @return serialCode
  **/
  @javax.annotation.Nullable
  public String getSerialCode() {
    return serialCode;
  }

  public void setSerialCode(String serialCode) {
    this.serialCode = serialCode;
  }


  public QuoteDocumentAnswerDto mask(BigDecimal mask) {
    this.mask = mask;
    return this;
  }

   /**
   * Mask used on the code of the document. The complete invoice identifier number is built from the serial code and the code. For example, for a serial code \&quot;F2023\&quot; and a code \&quot;1\&quot; the full identifier number that will appear in the PDF will be \&quot;F20231\&quot;. The mask allows for leading zeros to be included when constructing the complete ID number in the PDF. If we put a mask of 3, the full ID number will be \&quot;F2023001\&quot;
   * @return mask
  **/
  @javax.annotation.Nullable
  public BigDecimal getMask() {
    return mask;
  }

  public void setMask(BigDecimal mask) {
    this.mask = mask;
  }


  public QuoteDocumentAnswerDto code(BigDecimal code) {
    this.code = code;
    return this;
  }

   /**
   * Code/Number of the document
   * minimum: 0
   * @return code
  **/
  @javax.annotation.Nullable
  public BigDecimal getCode() {
    return code;
  }

  public void setCode(BigDecimal code) {
    this.code = code;
  }


  public QuoteDocumentAnswerDto identifier(String identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * The identifier of the document
   * @return identifier
  **/
  @javax.annotation.Nullable
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }


  public QuoteDocumentAnswerDto dueDate(String dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * The due date of the document
   * @return dueDate
  **/
  @javax.annotation.Nullable
  public String getDueDate() {
    return dueDate;
  }

  public void setDueDate(String dueDate) {
    this.dueDate = dueDate;
  }


  public QuoteDocumentAnswerDto reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * The reference of the document
   * @return reference
  **/
  @javax.annotation.Nullable
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }


  public QuoteDocumentAnswerDto total(DocumentTotalAnswerDto total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @javax.annotation.Nonnull
  public DocumentTotalAnswerDto getTotal() {
    return total;
  }

  public void setTotal(DocumentTotalAnswerDto total) {
    this.total = total;
  }


  public QuoteDocumentAnswerDto lines(List<DocumentLineAnswerDto> lines) {
    this.lines = lines;
    return this;
  }

  public QuoteDocumentAnswerDto addLinesItem(DocumentLineAnswerDto linesItem) {
    if (this.lines == null) {
      this.lines = new ArrayList<>();
    }
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Lines of the quote
   * @return lines
  **/
  @javax.annotation.Nonnull
  public List<DocumentLineAnswerDto> getLines() {
    return lines;
  }

  public void setLines(List<DocumentLineAnswerDto> lines) {
    this.lines = lines;
  }


  public QuoteDocumentAnswerDto visualLines(List<VisualLineDto> visualLines) {
    this.visualLines = visualLines;
    return this;
  }

  public QuoteDocumentAnswerDto addVisualLinesItem(VisualLineDto visualLinesItem) {
    if (this.visualLines == null) {
      this.visualLines = new ArrayList<>();
    }
    this.visualLines.add(visualLinesItem);
    return this;
  }

   /**
   * Visual Lines of the document
   * @return visualLines
  **/
  @javax.annotation.Nonnull
  public List<VisualLineDto> getVisualLines() {
    return visualLines;
  }

  public void setVisualLines(List<VisualLineDto> visualLines) {
    this.visualLines = visualLines;
  }


  public QuoteDocumentAnswerDto taxLines(List<DocumentTaxLineAnswerDto> taxLines) {
    this.taxLines = taxLines;
    return this;
  }

  public QuoteDocumentAnswerDto addTaxLinesItem(DocumentTaxLineAnswerDto taxLinesItem) {
    if (this.taxLines == null) {
      this.taxLines = new ArrayList<>();
    }
    this.taxLines.add(taxLinesItem);
    return this;
  }

   /**
   * Tax lines of the quote
   * @return taxLines
  **/
  @javax.annotation.Nonnull
  public List<DocumentTaxLineAnswerDto> getTaxLines() {
    return taxLines;
  }

  public void setTaxLines(List<DocumentTaxLineAnswerDto> taxLines) {
    this.taxLines = taxLines;
  }


  public QuoteDocumentAnswerDto additionalExpenses(List<AdditionalExpenseAnswerDto> additionalExpenses) {
    this.additionalExpenses = additionalExpenses;
    return this;
  }

  public QuoteDocumentAnswerDto addAdditionalExpensesItem(AdditionalExpenseAnswerDto additionalExpensesItem) {
    if (this.additionalExpenses == null) {
      this.additionalExpenses = new ArrayList<>();
    }
    this.additionalExpenses.add(additionalExpensesItem);
    return this;
  }

   /**
   * Additional expenses of the quote
   * @return additionalExpenses
  **/
  @javax.annotation.Nonnull
  public List<AdditionalExpenseAnswerDto> getAdditionalExpenses() {
    return additionalExpenses;
  }

  public void setAdditionalExpenses(List<AdditionalExpenseAnswerDto> additionalExpenses) {
    this.additionalExpenses = additionalExpenses;
  }


  public QuoteDocumentAnswerDto retentionPercentage(BigDecimal retentionPercentage) {
    this.retentionPercentage = retentionPercentage;
    return this;
  }

   /**
   * Percentage of retention
   * @return retentionPercentage
  **/
  @javax.annotation.Nonnull
  public BigDecimal getRetentionPercentage() {
    return retentionPercentage;
  }

  public void setRetentionPercentage(BigDecimal retentionPercentage) {
    this.retentionPercentage = retentionPercentage;
  }


  public QuoteDocumentAnswerDto retentionAmount(BigDecimal retentionAmount) {
    this.retentionAmount = retentionAmount;
    return this;
  }

   /**
   * Retention amount
   * @return retentionAmount
  **/
  @javax.annotation.Nonnull
  public BigDecimal getRetentionAmount() {
    return retentionAmount;
  }

  public void setRetentionAmount(BigDecimal retentionAmount) {
    this.retentionAmount = retentionAmount;
  }


  public QuoteDocumentAnswerDto paidAmount(BigDecimal paidAmount) {
    this.paidAmount = paidAmount;
    return this;
  }

   /**
   * Paid amount
   * @return paidAmount
  **/
  @javax.annotation.Nonnull
  public BigDecimal getPaidAmount() {
    return paidAmount;
  }

  public void setPaidAmount(BigDecimal paidAmount) {
    this.paidAmount = paidAmount;
  }


  public QuoteDocumentAnswerDto documentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
    return this;
  }

   /**
   * Type of the document
   * @return documentType
  **/
  @javax.annotation.Nullable
  public DocumentTypeEnum getDocumentType() {
    return documentType;
  }

  public void setDocumentType(DocumentTypeEnum documentType) {
    this.documentType = documentType;
  }


  public QuoteDocumentAnswerDto category(CategoryEnum category) {
    this.category = category;
    return this;
  }

   /**
   * Type of the document
   * @return category
  **/
  @javax.annotation.Nullable
  public CategoryEnum getCategory() {
    return category;
  }

  public void setCategory(CategoryEnum category) {
    this.category = category;
  }


  public QuoteDocumentAnswerDto contact(DocumentContactAnswerDto contact) {
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  @javax.annotation.Nonnull
  public DocumentContactAnswerDto getContact() {
    return contact;
  }

  public void setContact(DocumentContactAnswerDto contact) {
    this.contact = contact;
  }


  public QuoteDocumentAnswerDto paymentMethods(GetPaymentMethodDto paymentMethods) {
    this.paymentMethods = paymentMethods;
    return this;
  }

   /**
   * Get paymentMethods
   * @return paymentMethods
  **/
  @javax.annotation.Nonnull
  public GetPaymentMethodDto getPaymentMethods() {
    return paymentMethods;
  }

  public void setPaymentMethods(GetPaymentMethodDto paymentMethods) {
    this.paymentMethods = paymentMethods;
  }


  public QuoteDocumentAnswerDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the quote
   * @return status
  **/
  @javax.annotation.Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuoteDocumentAnswerDto quoteDocumentAnswerDto = (QuoteDocumentAnswerDto) o;
    return Objects.equals(this.id, quoteDocumentAnswerDto.id) &&
        Objects.equals(this.createdAt, quoteDocumentAnswerDto.createdAt) &&
        Objects.equals(this.updatedAt, quoteDocumentAnswerDto.updatedAt) &&
        Objects.equals(this.issuedDateTime, quoteDocumentAnswerDto.issuedDateTime) &&
        Objects.equals(this.issuedDate, quoteDocumentAnswerDto.issuedDate) &&
        Objects.equals(this.ownerInfo, quoteDocumentAnswerDto.ownerInfo) &&
        Objects.equals(this.currency, quoteDocumentAnswerDto.currency) &&
        Objects.equals(this.comments, quoteDocumentAnswerDto.comments) &&
        Objects.equals(this.serieId, quoteDocumentAnswerDto.serieId) &&
        Objects.equals(this.serialCode, quoteDocumentAnswerDto.serialCode) &&
        Objects.equals(this.mask, quoteDocumentAnswerDto.mask) &&
        Objects.equals(this.code, quoteDocumentAnswerDto.code) &&
        Objects.equals(this.identifier, quoteDocumentAnswerDto.identifier) &&
        Objects.equals(this.dueDate, quoteDocumentAnswerDto.dueDate) &&
        Objects.equals(this.reference, quoteDocumentAnswerDto.reference) &&
        Objects.equals(this.total, quoteDocumentAnswerDto.total) &&
        Objects.equals(this.lines, quoteDocumentAnswerDto.lines) &&
        Objects.equals(this.visualLines, quoteDocumentAnswerDto.visualLines) &&
        Objects.equals(this.taxLines, quoteDocumentAnswerDto.taxLines) &&
        Objects.equals(this.additionalExpenses, quoteDocumentAnswerDto.additionalExpenses) &&
        Objects.equals(this.retentionPercentage, quoteDocumentAnswerDto.retentionPercentage) &&
        Objects.equals(this.retentionAmount, quoteDocumentAnswerDto.retentionAmount) &&
        Objects.equals(this.paidAmount, quoteDocumentAnswerDto.paidAmount) &&
        Objects.equals(this.documentType, quoteDocumentAnswerDto.documentType) &&
        Objects.equals(this.category, quoteDocumentAnswerDto.category) &&
        Objects.equals(this.contact, quoteDocumentAnswerDto.contact) &&
        Objects.equals(this.paymentMethods, quoteDocumentAnswerDto.paymentMethods) &&
        Objects.equals(this.status, quoteDocumentAnswerDto.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, updatedAt, issuedDateTime, issuedDate, ownerInfo, currency, comments, serieId, serialCode, mask, code, identifier, dueDate, reference, total, lines, visualLines, taxLines, additionalExpenses, retentionPercentage, retentionAmount, paidAmount, documentType, category, contact, paymentMethods, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuoteDocumentAnswerDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    issuedDateTime: ").append(toIndentedString(issuedDateTime)).append("\n");
    sb.append("    issuedDate: ").append(toIndentedString(issuedDate)).append("\n");
    sb.append("    ownerInfo: ").append(toIndentedString(ownerInfo)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    serieId: ").append(toIndentedString(serieId)).append("\n");
    sb.append("    serialCode: ").append(toIndentedString(serialCode)).append("\n");
    sb.append("    mask: ").append(toIndentedString(mask)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    visualLines: ").append(toIndentedString(visualLines)).append("\n");
    sb.append("    taxLines: ").append(toIndentedString(taxLines)).append("\n");
    sb.append("    additionalExpenses: ").append(toIndentedString(additionalExpenses)).append("\n");
    sb.append("    retentionPercentage: ").append(toIndentedString(retentionPercentage)).append("\n");
    sb.append("    retentionAmount: ").append(toIndentedString(retentionAmount)).append("\n");
    sb.append("    paidAmount: ").append(toIndentedString(paidAmount)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("    paymentMethods: ").append(toIndentedString(paymentMethods)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("issuedDateTime");
    openapiFields.add("issuedDate");
    openapiFields.add("ownerInfo");
    openapiFields.add("currency");
    openapiFields.add("comments");
    openapiFields.add("serieId");
    openapiFields.add("serialCode");
    openapiFields.add("mask");
    openapiFields.add("code");
    openapiFields.add("identifier");
    openapiFields.add("dueDate");
    openapiFields.add("reference");
    openapiFields.add("total");
    openapiFields.add("lines");
    openapiFields.add("visualLines");
    openapiFields.add("taxLines");
    openapiFields.add("additionalExpenses");
    openapiFields.add("retentionPercentage");
    openapiFields.add("retentionAmount");
    openapiFields.add("paidAmount");
    openapiFields.add("documentType");
    openapiFields.add("category");
    openapiFields.add("contact");
    openapiFields.add("paymentMethods");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("updatedAt");
    openapiRequiredFields.add("ownerInfo");
    openapiRequiredFields.add("currency");
    openapiRequiredFields.add("dueDate");
    openapiRequiredFields.add("total");
    openapiRequiredFields.add("lines");
    openapiRequiredFields.add("visualLines");
    openapiRequiredFields.add("taxLines");
    openapiRequiredFields.add("additionalExpenses");
    openapiRequiredFields.add("retentionPercentage");
    openapiRequiredFields.add("retentionAmount");
    openapiRequiredFields.add("paidAmount");
    openapiRequiredFields.add("contact");
    openapiRequiredFields.add("paymentMethods");
    openapiRequiredFields.add("status");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to QuoteDocumentAnswerDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!QuoteDocumentAnswerDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in QuoteDocumentAnswerDto is not found in the empty JSON string", QuoteDocumentAnswerDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!QuoteDocumentAnswerDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `QuoteDocumentAnswerDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : QuoteDocumentAnswerDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("issuedDate") != null && !jsonObj.get("issuedDate").isJsonNull()) && !jsonObj.get("issuedDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `issuedDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("issuedDate").toString()));
      }
      // validate the required field `ownerInfo`
      BusinessBaseAnswerDto.validateJsonElement(jsonObj.get("ownerInfo"));
      if (!jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      // validate the required field `currency`
      CurrencyEnum.validateJsonElement(jsonObj.get("currency"));
      if ((jsonObj.get("comments") != null && !jsonObj.get("comments").isJsonNull()) && !jsonObj.get("comments").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comments` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comments").toString()));
      }
      if ((jsonObj.get("serieId") != null && !jsonObj.get("serieId").isJsonNull()) && !jsonObj.get("serieId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serieId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serieId").toString()));
      }
      if ((jsonObj.get("serialCode") != null && !jsonObj.get("serialCode").isJsonNull()) && !jsonObj.get("serialCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serialCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serialCode").toString()));
      }
      if ((jsonObj.get("identifier") != null && !jsonObj.get("identifier").isJsonNull()) && !jsonObj.get("identifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `identifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("identifier").toString()));
      }
      if ((jsonObj.get("dueDate") != null && !jsonObj.get("dueDate").isJsonNull()) && !jsonObj.get("dueDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dueDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dueDate").toString()));
      }
      if ((jsonObj.get("reference") != null && !jsonObj.get("reference").isJsonNull()) && !jsonObj.get("reference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reference").toString()));
      }
      // validate the required field `total`
      DocumentTotalAnswerDto.validateJsonElement(jsonObj.get("total"));
      // ensure the json data is an array
      if (!jsonObj.get("lines").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `lines` to be an array in the JSON string but got `%s`", jsonObj.get("lines").toString()));
      }

      JsonArray jsonArraylines = jsonObj.getAsJsonArray("lines");
      // validate the required field `lines` (array)
      for (int i = 0; i < jsonArraylines.size(); i++) {
        DocumentLineAnswerDto.validateJsonElement(jsonArraylines.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("visualLines").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `visualLines` to be an array in the JSON string but got `%s`", jsonObj.get("visualLines").toString()));
      }

      JsonArray jsonArrayvisualLines = jsonObj.getAsJsonArray("visualLines");
      // validate the required field `visualLines` (array)
      for (int i = 0; i < jsonArrayvisualLines.size(); i++) {
        VisualLineDto.validateJsonElement(jsonArrayvisualLines.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("taxLines").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `taxLines` to be an array in the JSON string but got `%s`", jsonObj.get("taxLines").toString()));
      }

      JsonArray jsonArraytaxLines = jsonObj.getAsJsonArray("taxLines");
      // validate the required field `taxLines` (array)
      for (int i = 0; i < jsonArraytaxLines.size(); i++) {
        DocumentTaxLineAnswerDto.validateJsonElement(jsonArraytaxLines.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("additionalExpenses").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `additionalExpenses` to be an array in the JSON string but got `%s`", jsonObj.get("additionalExpenses").toString()));
      }

      JsonArray jsonArrayadditionalExpenses = jsonObj.getAsJsonArray("additionalExpenses");
      // validate the required field `additionalExpenses` (array)
      for (int i = 0; i < jsonArrayadditionalExpenses.size(); i++) {
        AdditionalExpenseAnswerDto.validateJsonElement(jsonArrayadditionalExpenses.get(i));
      };
      if ((jsonObj.get("documentType") != null && !jsonObj.get("documentType").isJsonNull()) && !jsonObj.get("documentType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `documentType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("documentType").toString()));
      }
      // validate the optional field `documentType`
      if (jsonObj.get("documentType") != null && !jsonObj.get("documentType").isJsonNull()) {
        DocumentTypeEnum.validateJsonElement(jsonObj.get("documentType"));
      }
      if ((jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) && !jsonObj.get("category").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `category` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category").toString()));
      }
      // validate the optional field `category`
      if (jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) {
        CategoryEnum.validateJsonElement(jsonObj.get("category"));
      }
      // validate the required field `contact`
      DocumentContactAnswerDto.validateJsonElement(jsonObj.get("contact"));
      // validate the required field `paymentMethods`
      GetPaymentMethodDto.validateJsonElement(jsonObj.get("paymentMethods"));
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the required field `status`
      StatusEnum.validateJsonElement(jsonObj.get("status"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QuoteDocumentAnswerDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QuoteDocumentAnswerDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QuoteDocumentAnswerDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QuoteDocumentAnswerDto.class));

       return (TypeAdapter<T>) new TypeAdapter<QuoteDocumentAnswerDto>() {
           @Override
           public void write(JsonWriter out, QuoteDocumentAnswerDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public QuoteDocumentAnswerDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of QuoteDocumentAnswerDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of QuoteDocumentAnswerDto
  * @throws IOException if the JSON string is invalid with respect to QuoteDocumentAnswerDto
  */
  public static QuoteDocumentAnswerDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QuoteDocumentAnswerDto.class);
  }

 /**
  * Convert an instance of QuoteDocumentAnswerDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

