/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.facturasbillin.sdk.JSON;

/**
 * SortDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SortDto implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * Gets or Sets issuedDate
   */
  @JsonAdapter(IssuedDateEnum.Adapter.class)
  public enum IssuedDateEnum {
    ASC("ASC"),
    
    DESC("DESC");

    private String value;

    IssuedDateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static IssuedDateEnum fromValue(String value) {
      for (IssuedDateEnum b : IssuedDateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<IssuedDateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IssuedDateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IssuedDateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return IssuedDateEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      IssuedDateEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ISSUED_DATE = "issuedDate";
  @SerializedName(SERIALIZED_NAME_ISSUED_DATE)
  private IssuedDateEnum issuedDate;

  /**
   * Gets or Sets createdAt
   */
  @JsonAdapter(CreatedAtEnum.Adapter.class)
  public enum CreatedAtEnum {
    ASC("ASC"),
    
    DESC("DESC");

    private String value;

    CreatedAtEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CreatedAtEnum fromValue(String value) {
      for (CreatedAtEnum b : CreatedAtEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CreatedAtEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CreatedAtEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CreatedAtEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CreatedAtEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CreatedAtEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private CreatedAtEnum createdAt;

  /**
   * Gets or Sets updatedAt
   */
  @JsonAdapter(UpdatedAtEnum.Adapter.class)
  public enum UpdatedAtEnum {
    ASC("ASC"),
    
    DESC("DESC");

    private String value;

    UpdatedAtEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static UpdatedAtEnum fromValue(String value) {
      for (UpdatedAtEnum b : UpdatedAtEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<UpdatedAtEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final UpdatedAtEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public UpdatedAtEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return UpdatedAtEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      UpdatedAtEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private UpdatedAtEnum updatedAt;

  /**
   * Gets or Sets serialCode
   */
  @JsonAdapter(SerialCodeEnum.Adapter.class)
  public enum SerialCodeEnum {
    ASC("ASC"),
    
    DESC("DESC");

    private String value;

    SerialCodeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SerialCodeEnum fromValue(String value) {
      for (SerialCodeEnum b : SerialCodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SerialCodeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SerialCodeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SerialCodeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SerialCodeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      SerialCodeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SERIAL_CODE = "serialCode";
  @SerializedName(SERIALIZED_NAME_SERIAL_CODE)
  private SerialCodeEnum serialCode;

  /**
   * Gets or Sets code
   */
  @JsonAdapter(CodeEnum.Adapter.class)
  public enum CodeEnum {
    ASC("ASC"),
    
    DESC("DESC");

    private String value;

    CodeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CodeEnum fromValue(String value) {
      for (CodeEnum b : CodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CodeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CodeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CodeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CodeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CodeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private CodeEnum code;

  /**
   * Gets or Sets reference
   */
  @JsonAdapter(ReferenceEnum.Adapter.class)
  public enum ReferenceEnum {
    ASC("ASC"),
    
    DESC("DESC");

    private String value;

    ReferenceEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ReferenceEnum fromValue(String value) {
      for (ReferenceEnum b : ReferenceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ReferenceEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ReferenceEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ReferenceEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ReferenceEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ReferenceEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_REFERENCE = "reference";
  @SerializedName(SERIALIZED_NAME_REFERENCE)
  private ReferenceEnum reference;

  public SortDto() {
  }

  public SortDto issuedDate(IssuedDateEnum issuedDate) {
    this.issuedDate = issuedDate;
    return this;
  }

   /**
   * Get issuedDate
   * @return issuedDate
  **/
  @javax.annotation.Nullable
  public IssuedDateEnum getIssuedDate() {
    return issuedDate;
  }

  public void setIssuedDate(IssuedDateEnum issuedDate) {
    this.issuedDate = issuedDate;
  }


  public SortDto createdAt(CreatedAtEnum createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  public CreatedAtEnum getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(CreatedAtEnum createdAt) {
    this.createdAt = createdAt;
  }


  public SortDto updatedAt(UpdatedAtEnum updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  public UpdatedAtEnum getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(UpdatedAtEnum updatedAt) {
    this.updatedAt = updatedAt;
  }


  public SortDto serialCode(SerialCodeEnum serialCode) {
    this.serialCode = serialCode;
    return this;
  }

   /**
   * Get serialCode
   * @return serialCode
  **/
  @javax.annotation.Nullable
  public SerialCodeEnum getSerialCode() {
    return serialCode;
  }

  public void setSerialCode(SerialCodeEnum serialCode) {
    this.serialCode = serialCode;
  }


  public SortDto code(CodeEnum code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @javax.annotation.Nullable
  public CodeEnum getCode() {
    return code;
  }

  public void setCode(CodeEnum code) {
    this.code = code;
  }


  public SortDto reference(ReferenceEnum reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @javax.annotation.Nullable
  public ReferenceEnum getReference() {
    return reference;
  }

  public void setReference(ReferenceEnum reference) {
    this.reference = reference;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SortDto instance itself
   */
  public SortDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SortDto sortDto = (SortDto) o;
    return Objects.equals(this.issuedDate, sortDto.issuedDate) &&
        Objects.equals(this.createdAt, sortDto.createdAt) &&
        Objects.equals(this.updatedAt, sortDto.updatedAt) &&
        Objects.equals(this.serialCode, sortDto.serialCode) &&
        Objects.equals(this.code, sortDto.code) &&
        Objects.equals(this.reference, sortDto.reference)&&
        Objects.equals(this.additionalProperties, sortDto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issuedDate, createdAt, updatedAt, serialCode, code, reference, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SortDto {\n");
    sb.append("    issuedDate: ").append(toIndentedString(issuedDate)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    serialCode: ").append(toIndentedString(serialCode)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("issuedDate");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");
    openapiFields.add("serialCode");
    openapiFields.add("code");
    openapiFields.add("reference");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element. Made tolerant via the SDK template override:
  * any non-object payload (e.g. the API returning {@code []} where the spec
  * says object) is silently ignored, and field-level type mismatches are
  * swallowed, so a malformed field never crashes the whole DTO.
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SortDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null || jsonElement.isJsonNull()) {
        if (!SortDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SortDto is not found in the empty JSON string", SortDto.openapiRequiredFields.toString()));
        }
        return;
      }
      // SDK tolerance: when the API returns a shape other than a JSON object
      // (e.g. an empty array []), do not crash deserialization. The reflective
      // adapter will leave the field null and the caller can handle absence.
      if (!jsonElement.isJsonObject()) {
        return;
      }
      try {
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `issuedDate`
      if (jsonObj.get("issuedDate") != null && !jsonObj.get("issuedDate").isJsonNull() && jsonObj.get("issuedDate").isJsonPrimitive()) {
        IssuedDateEnum.validateJsonElement(jsonObj.get("issuedDate"));
      }
      // validate the optional field `createdAt`
      if (jsonObj.get("createdAt") != null && !jsonObj.get("createdAt").isJsonNull() && jsonObj.get("createdAt").isJsonPrimitive()) {
        CreatedAtEnum.validateJsonElement(jsonObj.get("createdAt"));
      }
      // validate the optional field `updatedAt`
      if (jsonObj.get("updatedAt") != null && !jsonObj.get("updatedAt").isJsonNull() && jsonObj.get("updatedAt").isJsonPrimitive()) {
        UpdatedAtEnum.validateJsonElement(jsonObj.get("updatedAt"));
      }
      // validate the optional field `serialCode`
      if (jsonObj.get("serialCode") != null && !jsonObj.get("serialCode").isJsonNull() && jsonObj.get("serialCode").isJsonPrimitive()) {
        SerialCodeEnum.validateJsonElement(jsonObj.get("serialCode"));
      }
      // validate the optional field `code`
      if (jsonObj.get("code") != null && !jsonObj.get("code").isJsonNull() && jsonObj.get("code").isJsonPrimitive()) {
        CodeEnum.validateJsonElement(jsonObj.get("code"));
      }
      // validate the optional field `reference`
      if (jsonObj.get("reference") != null && !jsonObj.get("reference").isJsonNull() && jsonObj.get("reference").isJsonPrimitive()) {
        ReferenceEnum.validateJsonElement(jsonObj.get("reference"));
      }
      } catch (RuntimeException ignored) {
        // SDK tolerance: per-field validation failures (unknown keys, wrong
        // primitive types, etc.) must not crash the whole response. The
        // reflective Gson adapter that runs next will leave problematic
        // fields null when conversion is impossible.
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SortDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SortDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SortDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SortDto.class));

       return (TypeAdapter<T>) new TypeAdapter<SortDto>() {
           @Override
           public void write(JsonWriter out, SortDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else if (entry.getValue() == null)
                   obj.add(entry.getKey(), null);
                 else {
                   JsonElement tree = gson.toJsonTree(entry.getValue());
                   if (tree.isJsonObject()) {
                     obj.add(entry.getKey(), tree.getAsJsonObject());
                   } else {
                     obj.add(entry.getKey(), tree);
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SortDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             // SDK tolerance: API may return a non-object shape (commonly `[]`)
             // where the spec declares this type. Don't crash — return null.
             if (jsonElement == null || jsonElement.isJsonNull() || !jsonElement.isJsonObject()) {
               return null;
             }
             try {
               validateJsonElement(jsonElement);
             } catch (RuntimeException ignored) {
               // SDK tolerance: validation already swallows internally, but
               // belt-and-braces in case a future change throws unexpectedly.
             }
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             SortDto instance;
             try {
               instance = thisAdapter.fromJsonTree(jsonObj);
             } catch (RuntimeException ignored) {
               // SDK tolerance: a single field with a wildly wrong shape can
               // make the reflective adapter throw. Better to lose the DTO
               // than to crash the entire API call.
               return null;
             }
             if (instance == null) {
               return null;
             }
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 try {
                   JsonElement value = entry.getValue();
                   if (value == null || value.isJsonNull()) {
                     instance.putAdditionalProperty(entry.getKey(), null);
                   } else if (value.isJsonPrimitive()) { // primitive type
                     if (value.getAsJsonPrimitive().isString())
                       instance.putAdditionalProperty(entry.getKey(), value.getAsString());
                     else if (value.getAsJsonPrimitive().isNumber())
                       instance.putAdditionalProperty(entry.getKey(), value.getAsNumber());
                     else if (value.getAsJsonPrimitive().isBoolean())
                       instance.putAdditionalProperty(entry.getKey(), value.getAsBoolean());
                     else
                       instance.putAdditionalProperty(entry.getKey(), value.toString());
                   } else if (value.isJsonArray()) {
                       instance.putAdditionalProperty(entry.getKey(), gson.fromJson(value, List.class));
                   } else { // JSON object
                       instance.putAdditionalProperty(entry.getKey(), gson.fromJson(value, HashMap.class));
                   }
                 } catch (RuntimeException ignored) {
                   // SDK tolerance: skip additional properties that can't be deserialized.
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SortDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SortDto
  * @throws IOException if the JSON string is invalid with respect to SortDto
  */
  public static SortDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SortDto.class);
  }

 /**
  * Convert an instance of SortDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

