/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.api;

import net.facturasbillin.sdk.ApiException;
import net.facturasbillin.sdk.model.AccountingAccountAnswerDto;
import net.facturasbillin.sdk.model.AccountingAccountListAnswerDto;
import net.facturasbillin.sdk.model.ApiBadRequestException;
import net.facturasbillin.sdk.model.ApiUnauthorizedException;
import java.math.BigDecimal;
import net.facturasbillin.sdk.model.CreateAccountingAccountDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountingAccountsApi
 */
@Disabled
public class AccountingAccountsApiTest {

    private final AccountingAccountsApi api = new AccountingAccountsApi();

    /**
     * Create an accounting account
     *
     * Endpoint to create an accounting account
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAccountingAccountTest() throws ApiException {
        CreateAccountingAccountDto createAccountingAccountDto = null;
        AccountingAccountAnswerDto response = api.createAccountingAccount(createAccountingAccountDto);
        // TODO: test validations
    }

    /**
     * Get the accounting accounts list
     *
     * Endpoint to get the accounting accounts list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountingAccountListTest() throws ApiException {
        String queryType = null;
        String sortCreatedAt = null;
        String sortUpdatedAt = null;
        String sortAlias = null;
        BigDecimal limit = null;
        BigDecimal offset = null;
        AccountingAccountListAnswerDto response = api.getAccountingAccountList(queryType, sortCreatedAt, sortUpdatedAt, sortAlias, limit, offset);
        // TODO: test validations
    }

}
