/*
 * Billin Api
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package net.facturasbillin.sdk.api;

import net.facturasbillin.sdk.ApiCallback;
import net.facturasbillin.sdk.ApiClient;
import net.facturasbillin.sdk.ApiException;
import net.facturasbillin.sdk.ApiResponse;
import net.facturasbillin.sdk.Configuration;
import net.facturasbillin.sdk.Pair;
import net.facturasbillin.sdk.ProgressRequestBody;
import net.facturasbillin.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;

import javax.validation.constraints.*;
import javax.validation.Valid;

import net.facturasbillin.sdk.model.ApiBadRequestException;
import net.facturasbillin.sdk.model.ApiUnauthorizedException;
import net.facturasbillin.sdk.model.AuthInfoAnswerDto;
import net.facturasbillin.sdk.model.RequestTokenUserApiCredentialDto;
import net.facturasbillin.sdk.model.TokenAnswerDto;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AuthApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AuthApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AuthApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for authControllerGetInfoV1
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call authControllerGetInfoV1Call(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/auth/info";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearer" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call authControllerGetInfoV1ValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return authControllerGetInfoV1Call(_callback);

    }

    /**
     * Get user info
     * Endpoint that gets the basic info from the user that generated the API credentials
     * @return AuthInfoAnswerDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public AuthInfoAnswerDto authControllerGetInfoV1() throws ApiException {
        ApiResponse<AuthInfoAnswerDto> localVarResp = authControllerGetInfoV1WithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get user info
     * Endpoint that gets the basic info from the user that generated the API credentials
     * @return ApiResponse&lt;AuthInfoAnswerDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AuthInfoAnswerDto> authControllerGetInfoV1WithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = authControllerGetInfoV1ValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<AuthInfoAnswerDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get user info (asynchronously)
     * Endpoint that gets the basic info from the user that generated the API credentials
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call authControllerGetInfoV1Async(final ApiCallback<AuthInfoAnswerDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = authControllerGetInfoV1ValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<AuthInfoAnswerDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for authControllerGetTokenV1
     * @param requestTokenUserApiCredentialDto Currently there are three authentication flows: client_credentials, password and refresh_token. Not all of them are available to all users (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call authControllerGetTokenV1Call(RequestTokenUserApiCredentialDto requestTokenUserApiCredentialDto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = requestTokenUserApiCredentialDto;

        // create path and map variables
        String localVarPath = "/v1/auth/token";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call authControllerGetTokenV1ValidateBeforeCall(RequestTokenUserApiCredentialDto requestTokenUserApiCredentialDto, final ApiCallback _callback) throws ApiException {
        return authControllerGetTokenV1Call(requestTokenUserApiCredentialDto, _callback);

    }

    /**
     * OAuth2 authentication
     * Endpoint that validates credentials following the flows specified in OAuth2. If validates succesfully, returns an access token and a refresh token
     * @param requestTokenUserApiCredentialDto Currently there are three authentication flows: client_credentials, password and refresh_token. Not all of them are available to all users (optional)
     * @return TokenAnswerDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public TokenAnswerDto authControllerGetTokenV1(RequestTokenUserApiCredentialDto requestTokenUserApiCredentialDto) throws ApiException {
        ApiResponse<TokenAnswerDto> localVarResp = authControllerGetTokenV1WithHttpInfo(requestTokenUserApiCredentialDto);
        return localVarResp.getData();
    }

    /**
     * OAuth2 authentication
     * Endpoint that validates credentials following the flows specified in OAuth2. If validates succesfully, returns an access token and a refresh token
     * @param requestTokenUserApiCredentialDto Currently there are three authentication flows: client_credentials, password and refresh_token. Not all of them are available to all users (optional)
     * @return ApiResponse&lt;TokenAnswerDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TokenAnswerDto> authControllerGetTokenV1WithHttpInfo(RequestTokenUserApiCredentialDto requestTokenUserApiCredentialDto) throws ApiException {
        okhttp3.Call localVarCall = authControllerGetTokenV1ValidateBeforeCall(requestTokenUserApiCredentialDto, null);
        Type localVarReturnType = new TypeToken<TokenAnswerDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * OAuth2 authentication (asynchronously)
     * Endpoint that validates credentials following the flows specified in OAuth2. If validates succesfully, returns an access token and a refresh token
     * @param requestTokenUserApiCredentialDto Currently there are three authentication flows: client_credentials, password and refresh_token. Not all of them are available to all users (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call authControllerGetTokenV1Async(RequestTokenUserApiCredentialDto requestTokenUserApiCredentialDto, final ApiCallback<TokenAnswerDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = authControllerGetTokenV1ValidateBeforeCall(requestTokenUserApiCredentialDto, _callback);
        Type localVarReturnType = new TypeToken<TokenAnswerDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
