<?php
/**
 * SortDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  FacturasBillin\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Billin Api
 *
 * The integration API documentation
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FacturasBillin\SDK\Model;

use \ArrayAccess;
use \FacturasBillin\SDK\ObjectSerializer;

/**
 * SortDto Class Doc Comment
 *
 * @category Class
 * @package  FacturasBillin\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SortDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SortDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'issued_date' => 'string',
        'created_at' => 'string',
        'updated_at' => 'string',
        'serial_code' => 'string',
        'code' => 'string',
        'reference' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'issued_date' => null,
        'created_at' => null,
        'updated_at' => null,
        'serial_code' => null,
        'code' => null,
        'reference' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'issued_date' => false,
        'created_at' => false,
        'updated_at' => false,
        'serial_code' => false,
        'code' => false,
        'reference' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'issued_date' => 'issuedDate',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'serial_code' => 'serialCode',
        'code' => 'code',
        'reference' => 'reference'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'issued_date' => 'setIssuedDate',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'serial_code' => 'setSerialCode',
        'code' => 'setCode',
        'reference' => 'setReference'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'issued_date' => 'getIssuedDate',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'serial_code' => 'getSerialCode',
        'code' => 'getCode',
        'reference' => 'getReference'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ISSUED_DATE_ASC = 'ASC';
    public const ISSUED_DATE_DESC = 'DESC';
    public const CREATED_AT_ASC = 'ASC';
    public const CREATED_AT_DESC = 'DESC';
    public const UPDATED_AT_ASC = 'ASC';
    public const UPDATED_AT_DESC = 'DESC';
    public const SERIAL_CODE_ASC = 'ASC';
    public const SERIAL_CODE_DESC = 'DESC';
    public const CODE_ASC = 'ASC';
    public const CODE_DESC = 'DESC';
    public const REFERENCE_ASC = 'ASC';
    public const REFERENCE_DESC = 'DESC';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIssuedDateAllowableValues()
    {
        return [
            self::ISSUED_DATE_ASC,
            self::ISSUED_DATE_DESC,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCreatedAtAllowableValues()
    {
        return [
            self::CREATED_AT_ASC,
            self::CREATED_AT_DESC,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUpdatedAtAllowableValues()
    {
        return [
            self::UPDATED_AT_ASC,
            self::UPDATED_AT_DESC,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSerialCodeAllowableValues()
    {
        return [
            self::SERIAL_CODE_ASC,
            self::SERIAL_CODE_DESC,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCodeAllowableValues()
    {
        return [
            self::CODE_ASC,
            self::CODE_DESC,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getReferenceAllowableValues()
    {
        return [
            self::REFERENCE_ASC,
            self::REFERENCE_DESC,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('issued_date', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('serial_code', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getIssuedDateAllowableValues();
        if (!is_null($this->container['issued_date']) && !in_array($this->container['issued_date'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'issued_date', must be one of '%s'",
                $this->container['issued_date'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCreatedAtAllowableValues();
        if (!is_null($this->container['created_at']) && !in_array($this->container['created_at'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'created_at', must be one of '%s'",
                $this->container['created_at'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getUpdatedAtAllowableValues();
        if (!is_null($this->container['updated_at']) && !in_array($this->container['updated_at'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'updated_at', must be one of '%s'",
                $this->container['updated_at'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSerialCodeAllowableValues();
        if (!is_null($this->container['serial_code']) && !in_array($this->container['serial_code'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'serial_code', must be one of '%s'",
                $this->container['serial_code'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCodeAllowableValues();
        if (!is_null($this->container['code']) && !in_array($this->container['code'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'code', must be one of '%s'",
                $this->container['code'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getReferenceAllowableValues();
        if (!is_null($this->container['reference']) && !in_array($this->container['reference'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'reference', must be one of '%s'",
                $this->container['reference'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets issued_date
     *
     * @return string|null
     */
    public function getIssuedDate()
    {
        return $this->container['issued_date'];
    }

    /**
     * Sets issued_date
     *
     * @param string|null $issued_date issued_date
     *
     * @return self
     */
    public function setIssuedDate($issued_date)
    {
        if (is_null($issued_date)) {
            throw new \InvalidArgumentException('non-nullable issued_date cannot be null');
        }
        $allowedValues = $this->getIssuedDateAllowableValues();
        if (!in_array($issued_date, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'issued_date', must be one of '%s'",
                    $issued_date,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['issued_date'] = $issued_date;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $allowedValues = $this->getCreatedAtAllowableValues();
        if (!in_array($created_at, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'created_at', must be one of '%s'",
                    $created_at,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return string|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param string|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $allowedValues = $this->getUpdatedAtAllowableValues();
        if (!in_array($updated_at, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'updated_at', must be one of '%s'",
                    $updated_at,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets serial_code
     *
     * @return string|null
     */
    public function getSerialCode()
    {
        return $this->container['serial_code'];
    }

    /**
     * Sets serial_code
     *
     * @param string|null $serial_code serial_code
     *
     * @return self
     */
    public function setSerialCode($serial_code)
    {
        if (is_null($serial_code)) {
            throw new \InvalidArgumentException('non-nullable serial_code cannot be null');
        }
        $allowedValues = $this->getSerialCodeAllowableValues();
        if (!in_array($serial_code, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'serial_code', must be one of '%s'",
                    $serial_code,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['serial_code'] = $serial_code;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code code
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $allowedValues = $this->getCodeAllowableValues();
        if (!in_array($code, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'code', must be one of '%s'",
                    $code,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string|null
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string|null $reference reference
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            throw new \InvalidArgumentException('non-nullable reference cannot be null');
        }
        $allowedValues = $this->getReferenceAllowableValues();
        if (!in_array($reference, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'reference', must be one of '%s'",
                    $reference,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['reference'] = $reference;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


